{"asctime": "2020-06-29 06:16:52,789", "levelname": "DEBUG", "message": "ApplyDataModel :Class:ApplyDataModel"}
{"asctime": "2020-06-29 06:16:52,791", "levelname": "DEBUG", "message": "ApplyDataModel :loaded config for ApplyDataModel from C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.json"}
{"asctime": "2020-06-29 06:16:52,792", "levelname": "DEBUG", "message": "ApplyDataModel :C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel/schemas"}
{"asctime": "2020-06-29 06:16:52,792", "levelname": "DEBUG", "message": "ApplyDataModel :C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel/schemas/prjs/prjs.gdb"}
{"asctime": "2020-06-29 06:17:19,777", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 33 to Feet"}
{"asctime": "2020-06-29 06:17:19,777", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:19,777", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:20,336", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 34 to Feet"}
{"asctime": "2020-06-29 06:17:20,336", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:20,336", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:20,877", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 35 to Feet"}
{"asctime": "2020-06-29 06:17:20,877", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:20,877", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:21,428", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 36 to Feet"}
{"asctime": "2020-06-29 06:17:21,428", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:21,428", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:21,972", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 37 to Feet"}
{"asctime": "2020-06-29 06:17:21,972", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:21,972", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:22,519", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 38 to Feet"}
{"asctime": "2020-06-29 06:17:22,519", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:22,520", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:23,077", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 39 to Feet"}
{"asctime": "2020-06-29 06:17:23,077", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:23,077", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:23,637", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 40 to Feet"}
{"asctime": "2020-06-29 06:17:23,637", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:23,637", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:23,752", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain Inches"}
{"asctime": "2020-06-29 06:17:23,752", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000837: The workspace is not the correct workspace type.\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-06-29 06:17:23,753", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 125, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000837: The workspace is not the correct workspace type.\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-06-29 06:17:24,299", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 0 to Inches"}
{"asctime": "2020-06-29 06:17:24,299", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:24,300", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:24,842", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 1 to Inches"}
{"asctime": "2020-06-29 06:17:24,842", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:24,842", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:25,387", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 2 to Inches"}
{"asctime": "2020-06-29 06:17:25,387", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:25,387", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:25,935", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 3 to Inches"}
{"asctime": "2020-06-29 06:17:25,935", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:25,935", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:26,481", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 4 to Inches"}
{"asctime": "2020-06-29 06:17:26,481", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:26,481", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:27,026", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 5 to Inches"}
{"asctime": "2020-06-29 06:17:27,026", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:27,026", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:27,582", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 6 to Inches"}
{"asctime": "2020-06-29 06:17:27,583", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:27,583", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:28,129", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 7 to Inches"}
{"asctime": "2020-06-29 06:17:28,130", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:28,130", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:28,649", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 8 to Inches"}
{"asctime": "2020-06-29 06:17:28,650", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:28,650", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:28,773", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 9 to Inches"}
{"asctime": "2020-06-29 06:17:28,774", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000800: The value is not a member of ApprovalStatus | Feet | RouteBuildType.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:28,774", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000800: The value is not a member of ApprovalStatus | Feet | RouteBuildType.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:28,912", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 10 to Inches"}
{"asctime": "2020-06-29 06:17:28,913", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000800: The value is not a member of ApprovalStatus | Feet | RouteBuildType.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:28,913", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000800: The value is not a member of ApprovalStatus | Feet | RouteBuildType.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:29,053", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 11 to Inches"}
{"asctime": "2020-06-29 06:17:29,053", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000800: The value is not a member of ApprovalStatus | Feet | RouteBuildType.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:17:29,054", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 133, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000800: The value is not a member of ApprovalStatus | Feet | RouteBuildType.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-06-29 06:18:05,565", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'Anchor', 'geometry': 'POINT', 'spatialref': 2277, 'fields': 'anchor.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False, 'gpsmetadata': True}"}
{"asctime": "2020-06-29 06:18:05,597", "levelname": "DEBUG", "message": "ApplyDataModel :Creating feature class Anchor"}
{"asctime": "2020-06-29 06:18:06,991", "levelname": "DEBUG", "message": "ApplyDataModel :Anchor created"}
{"asctime": "2020-06-29 06:18:06,993", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Anchor"}
{"asctime": "2020-06-29 06:18:06,994", "levelname": "DEBUG", "message": "ApplyDataModel :Applying AnchorId"}
{"asctime": "2020-06-29 06:18:08,030", "levelname": "DEBUG", "message": "ApplyDataModel :Field AnchorId added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Anchor"}
{"asctime": "2020-06-29 06:18:08,030", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Lead"}
{"asctime": "2020-06-29 06:18:09,207", "levelname": "DEBUG", "message": "ApplyDataModel :Field Lead added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Anchor"}
{"asctime": "2020-06-29 06:18:09,208", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Height"}
{"asctime": "2020-06-29 06:18:10,503", "levelname": "DEBUG", "message": "ApplyDataModel :Field Height added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Anchor"}
{"asctime": "2020-06-29 06:18:10,504", "levelname": "DEBUG", "message": "ApplyDataModel :Applying PoleNumber"}
{"asctime": "2020-06-29 06:18:11,712", "levelname": "DEBUG", "message": "ApplyDataModel :Field PoleNumber added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Anchor"}
{"asctime": "2020-06-29 06:18:11,712", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Globals Ids."}
{"asctime": "2020-06-29 06:18:13,225", "levelname": "DEBUG", "message": "ApplyDataModel :Global Ids done."}
{"asctime": "2020-06-29 06:18:13,225", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Editor tracking fields."}
{"asctime": "2020-06-29 06:18:15,651", "levelname": "DEBUG", "message": "ApplyDataModel :Editor tracking enabled."}
{"asctime": "2020-06-29 06:18:15,652", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling archiving."}
{"asctime": "2020-06-29 06:18:15,978", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:18:15,979", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 249, in _manage_database_item\n    arcpy.EnableArchiving_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 209, in EnableArchiving\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 206, in EnableArchiving\n    retval = convertArcObjectToPythonObject(gp.EnableArchiving_management(*gp_fixargs((in_dataset,), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:18:15,980", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling GPS metadata."}
{"asctime": "2020-06-29 06:18:56,993", "levelname": "DEBUG", "message": "ApplyDataModel :GPS metadata enabled."}
{"asctime": "2020-06-29 06:18:56,993", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'Assembly', 'geometry': '', 'spatialref': '', 'fields': 'assemblyfielding.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False, 'gpsmetadata': False}"}
{"asctime": "2020-06-29 06:18:57,019", "levelname": "DEBUG", "message": "ApplyDataModel :Creating table Assembly"}
{"asctime": "2020-06-29 06:18:58,327", "levelname": "DEBUG", "message": "ApplyDataModel :Assembly created"}
{"asctime": "2020-06-29 06:18:58,329", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Assembly"}
{"asctime": "2020-06-29 06:18:58,329", "levelname": "DEBUG", "message": "ApplyDataModel :Applying AssemblyId"}
{"asctime": "2020-06-29 06:18:59,172", "levelname": "DEBUG", "message": "ApplyDataModel :Field AssemblyId added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Assembly"}
{"asctime": "2020-06-29 06:18:59,172", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Type"}
{"asctime": "2020-06-29 06:19:00,042", "levelname": "DEBUG", "message": "ApplyDataModel :Field Type added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Assembly"}
{"asctime": "2020-06-29 06:19:00,042", "levelname": "DEBUG", "message": "ApplyDataModel :Applying StructureId"}
{"asctime": "2020-06-29 06:19:01,160", "levelname": "DEBUG", "message": "ApplyDataModel :Field StructureId added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Assembly"}
{"asctime": "2020-06-29 06:19:01,162", "levelname": "DEBUG", "message": "ApplyDataModel :Applying FieldingRUSCode"}
{"asctime": "2020-06-29 06:19:02,448", "levelname": "DEBUG", "message": "ApplyDataModel :Field FieldingRUSCode added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Assembly"}
{"asctime": "2020-06-29 06:19:02,449", "levelname": "DEBUG", "message": "ApplyDataModel :Applying DesignRUSCode"}
{"asctime": "2020-06-29 06:19:03,968", "levelname": "DEBUG", "message": "ApplyDataModel :Field DesignRUSCode added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Assembly"}
{"asctime": "2020-06-29 06:19:03,968", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Globals Ids."}
{"asctime": "2020-06-29 06:19:05,482", "levelname": "DEBUG", "message": "ApplyDataModel :Global Ids done."}
{"asctime": "2020-06-29 06:19:05,483", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Editor tracking fields."}
{"asctime": "2020-06-29 06:19:07,214", "levelname": "DEBUG", "message": "ApplyDataModel :Editor tracking enabled."}
{"asctime": "2020-06-29 06:19:07,214", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling archiving."}
{"asctime": "2020-06-29 06:19:07,476", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:19:07,477", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 249, in _manage_database_item\n    arcpy.EnableArchiving_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 209, in EnableArchiving\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 206, in EnableArchiving\n    retval = convertArcObjectToPythonObject(gp.EnableArchiving_management(*gp_fixargs((in_dataset,), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:19:07,478", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'Comment', 'geometry': '', 'spatialref': '', 'fields': 'comment.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False, 'gpsmetadata': False}"}
{"asctime": "2020-06-29 06:19:07,510", "levelname": "DEBUG", "message": "ApplyDataModel :Creating table Comment"}
{"asctime": "2020-06-29 06:19:08,899", "levelname": "DEBUG", "message": "ApplyDataModel :Comment created"}
{"asctime": "2020-06-29 06:19:08,901", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Comment"}
{"asctime": "2020-06-29 06:19:08,902", "levelname": "DEBUG", "message": "ApplyDataModel :Applying CommentId"}
{"asctime": "2020-06-29 06:19:09,755", "levelname": "DEBUG", "message": "ApplyDataModel :Field CommentId added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Comment"}
{"asctime": "2020-06-29 06:19:09,755", "levelname": "DEBUG", "message": "ApplyDataModel :Applying FeatureId"}
{"asctime": "2020-06-29 06:19:10,614", "levelname": "DEBUG", "message": "ApplyDataModel :Field FeatureId added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Comment"}
{"asctime": "2020-06-29 06:19:10,615", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Comment"}
{"asctime": "2020-06-29 06:19:11,587", "levelname": "DEBUG", "message": "ApplyDataModel :Field Comment added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Comment"}
{"asctime": "2020-06-29 06:19:11,588", "levelname": "DEBUG", "message": "ApplyDataModel :Applying CommentType"}
{"asctime": "2020-06-29 06:19:12,573", "levelname": "DEBUG", "message": "ApplyDataModel :Field CommentType added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Comment"}
{"asctime": "2020-06-29 06:19:12,573", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Globals Ids."}
{"asctime": "2020-06-29 06:19:14,113", "levelname": "DEBUG", "message": "ApplyDataModel :Global Ids done."}
{"asctime": "2020-06-29 06:19:14,114", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Editor tracking fields."}
{"asctime": "2020-06-29 06:19:16,444", "levelname": "DEBUG", "message": "ApplyDataModel :Editor tracking enabled."}
{"asctime": "2020-06-29 06:19:16,445", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling archiving."}
{"asctime": "2020-06-29 06:19:16,757", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:19:16,757", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 249, in _manage_database_item\n    arcpy.EnableArchiving_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 209, in EnableArchiving\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 206, in EnableArchiving\n    retval = convertArcObjectToPythonObject(gp.EnableArchiving_management(*gp_fixargs((in_dataset,), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:19:16,758", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'Clearance', 'geometry': 'POINT', 'spatialref': 2277, 'fields': 'clearance.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False, 'gpsmetadata': True}"}
{"asctime": "2020-06-29 06:19:16,786", "levelname": "DEBUG", "message": "ApplyDataModel :Creating feature class Clearance"}
{"asctime": "2020-06-29 06:19:18,199", "levelname": "DEBUG", "message": "ApplyDataModel :Clearance created"}
{"asctime": "2020-06-29 06:19:18,202", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Clearance"}
{"asctime": "2020-06-29 06:19:18,202", "levelname": "DEBUG", "message": "ApplyDataModel :Applying ClearanceId"}
{"asctime": "2020-06-29 06:19:19,263", "levelname": "DEBUG", "message": "ApplyDataModel :Field ClearanceId added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Clearance"}
{"asctime": "2020-06-29 06:19:19,263", "levelname": "DEBUG", "message": "ApplyDataModel :Applying CrossingType"}
{"asctime": "2020-06-29 06:19:20,447", "levelname": "DEBUG", "message": "ApplyDataModel :Field CrossingType added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Clearance"}
{"asctime": "2020-06-29 06:19:20,447", "levelname": "DEBUG", "message": "ApplyDataModel :Applying MidspanType"}
{"asctime": "2020-06-29 06:19:21,747", "levelname": "DEBUG", "message": "ApplyDataModel :Field MidspanType added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Clearance"}
{"asctime": "2020-06-29 06:19:21,747", "levelname": "DEBUG", "message": "ApplyDataModel :Applying ClearanceFeet"}
{"asctime": "2020-06-29 06:19:23,033", "levelname": "DEBUG", "message": "ApplyDataModel :Field ClearanceFeet added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Clearance"}
{"asctime": "2020-06-29 06:19:23,034", "levelname": "DEBUG", "message": "ApplyDataModel :Applying ClearanceInches"}
{"asctime": "2020-06-29 06:19:24,251", "levelname": "DEBUG", "message": "ApplyDataModel :Field ClearanceInches added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Clearance"}
{"asctime": "2020-06-29 06:19:24,251", "levelname": "DEBUG", "message": "ApplyDataModel :Applying ClearanceOK"}
{"asctime": "2020-06-29 06:19:25,533", "levelname": "DEBUG", "message": "ApplyDataModel :Field ClearanceOK added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Clearance"}
{"asctime": "2020-06-29 06:19:25,533", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Globals Ids."}
{"asctime": "2020-06-29 06:19:27,324", "levelname": "DEBUG", "message": "ApplyDataModel :Global Ids done."}
{"asctime": "2020-06-29 06:19:27,324", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Editor tracking fields."}
{"asctime": "2020-06-29 06:19:29,849", "levelname": "DEBUG", "message": "ApplyDataModel :Editor tracking enabled."}
{"asctime": "2020-06-29 06:19:29,850", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling archiving."}
{"asctime": "2020-06-29 06:19:30,189", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:19:30,189", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 249, in _manage_database_item\n    arcpy.EnableArchiving_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 209, in EnableArchiving\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 206, in EnableArchiving\n    retval = convertArcObjectToPythonObject(gp.EnableArchiving_management(*gp_fixargs((in_dataset,), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:19:30,190", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling GPS metadata."}
{"asctime": "2020-06-29 06:20:01,108", "levelname": "DEBUG", "message": "ApplyDataModel :GPS metadata enabled."}
{"asctime": "2020-06-29 06:20:01,109", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'FieldingAreaMarker', 'geometry': 'POLYGON', 'spatialref': 2277, 'fields': 'fieldingareamarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': True, 'gpsmetadata': False}"}
{"asctime": "2020-06-29 06:20:01,138", "levelname": "DEBUG", "message": "ApplyDataModel :Creating feature class FieldingAreaMarker"}
{"asctime": "2020-06-29 06:20:02,504", "levelname": "DEBUG", "message": "ApplyDataModel :FieldingAreaMarker created"}
{"asctime": "2020-06-29 06:20:02,506", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/FieldingAreaMarker"}
{"asctime": "2020-06-29 06:20:02,507", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Label"}
{"asctime": "2020-06-29 06:20:03,627", "levelname": "DEBUG", "message": "ApplyDataModel :Field Label added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/FieldingAreaMarker"}
{"asctime": "2020-06-29 06:20:03,627", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Comment"}
{"asctime": "2020-06-29 06:20:04,683", "levelname": "DEBUG", "message": "ApplyDataModel :Field Comment added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/FieldingAreaMarker"}
{"asctime": "2020-06-29 06:20:04,684", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Globals Ids."}
{"asctime": "2020-06-29 06:20:06,227", "levelname": "DEBUG", "message": "ApplyDataModel :Global Ids done."}
{"asctime": "2020-06-29 06:20:06,227", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Editor tracking fields."}
{"asctime": "2020-06-29 06:20:08,073", "levelname": "DEBUG", "message": "ApplyDataModel :Editor tracking enabled."}
{"asctime": "2020-06-29 06:20:08,074", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling archiving."}
{"asctime": "2020-06-29 06:20:08,369", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:20:08,369", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 249, in _manage_database_item\n    arcpy.EnableArchiving_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 209, in EnableArchiving\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 206, in EnableArchiving\n    retval = convertArcObjectToPythonObject(gp.EnableArchiving_management(*gp_fixargs((in_dataset,), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:20:08,370", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling attachments."}
{"asctime": "2020-06-29 06:20:09,728", "levelname": "DEBUG", "message": "ApplyDataModel :Attachments enabled."}
{"asctime": "2020-06-29 06:20:09,729", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'FieldingPointMarker', 'geometry': 'POINT', 'spatialref': 2277, 'fields': 'fieldingpointmarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': True, 'gpsmetadata': False}"}
{"asctime": "2020-06-29 06:20:09,753", "levelname": "DEBUG", "message": "ApplyDataModel :Creating feature class FieldingPointMarker"}
{"asctime": "2020-06-29 06:20:11,013", "levelname": "DEBUG", "message": "ApplyDataModel :FieldingPointMarker created"}
{"asctime": "2020-06-29 06:20:11,015", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/FieldingPointMarker"}
{"asctime": "2020-06-29 06:20:11,015", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Label"}
{"asctime": "2020-06-29 06:20:12,289", "levelname": "DEBUG", "message": "ApplyDataModel :Field Label added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/FieldingPointMarker"}
{"asctime": "2020-06-29 06:20:12,289", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Comment"}
{"asctime": "2020-06-29 06:20:13,369", "levelname": "DEBUG", "message": "ApplyDataModel :Field Comment added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/FieldingPointMarker"}
{"asctime": "2020-06-29 06:20:13,369", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Globals Ids."}
{"asctime": "2020-06-29 06:20:14,777", "levelname": "DEBUG", "message": "ApplyDataModel :Global Ids done."}
{"asctime": "2020-06-29 06:20:14,777", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Editor tracking fields."}
{"asctime": "2020-06-29 06:20:16,464", "levelname": "DEBUG", "message": "ApplyDataModel :Editor tracking enabled."}
{"asctime": "2020-06-29 06:20:16,464", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling archiving."}
{"asctime": "2020-06-29 06:20:16,777", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:20:16,777", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 249, in _manage_database_item\n    arcpy.EnableArchiving_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 209, in EnableArchiving\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 206, in EnableArchiving\n    retval = convertArcObjectToPythonObject(gp.EnableArchiving_management(*gp_fixargs((in_dataset,), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:20:16,778", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling attachments."}
{"asctime": "2020-06-29 06:20:18,712", "levelname": "DEBUG", "message": "ApplyDataModel :Attachments enabled."}
{"asctime": "2020-06-29 06:20:18,713", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'FieldingLineMarker', 'geometry': 'POLYLINE', 'spatialref': 2277, 'fields': 'fieldinglinemarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': True, 'gpsmetadata': False}"}
{"asctime": "2020-06-29 06:20:18,747", "levelname": "DEBUG", "message": "ApplyDataModel :Creating feature class FieldingLineMarker"}
{"asctime": "2020-06-29 06:20:20,202", "levelname": "DEBUG", "message": "ApplyDataModel :FieldingLineMarker created"}
{"asctime": "2020-06-29 06:20:20,204", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/FieldingLineMarker"}
{"asctime": "2020-06-29 06:20:20,205", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Label"}
{"asctime": "2020-06-29 06:20:21,315", "levelname": "DEBUG", "message": "ApplyDataModel :Field Label added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/FieldingLineMarker"}
{"asctime": "2020-06-29 06:20:21,315", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Comment"}
{"asctime": "2020-06-29 06:20:22,476", "levelname": "DEBUG", "message": "ApplyDataModel :Field Comment added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/FieldingLineMarker"}
{"asctime": "2020-06-29 06:20:22,477", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Type"}
{"asctime": "2020-06-29 06:20:23,657", "levelname": "DEBUG", "message": "ApplyDataModel :Field Type added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/FieldingLineMarker"}
{"asctime": "2020-06-29 06:20:23,658", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Globals Ids."}
{"asctime": "2020-06-29 06:20:25,223", "levelname": "DEBUG", "message": "ApplyDataModel :Global Ids done."}
{"asctime": "2020-06-29 06:20:25,223", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Editor tracking fields."}
{"asctime": "2020-06-29 06:20:26,931", "levelname": "DEBUG", "message": "ApplyDataModel :Editor tracking enabled."}
{"asctime": "2020-06-29 06:20:26,931", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling archiving."}
{"asctime": "2020-06-29 06:20:27,235", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:20:27,235", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 249, in _manage_database_item\n    arcpy.EnableArchiving_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 209, in EnableArchiving\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 206, in EnableArchiving\n    retval = convertArcObjectToPythonObject(gp.EnableArchiving_management(*gp_fixargs((in_dataset,), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:20:27,236", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling attachments."}
{"asctime": "2020-06-29 06:20:28,758", "levelname": "DEBUG", "message": "ApplyDataModel :Attachments enabled."}
{"asctime": "2020-06-29 06:20:28,758", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'MakeReadyCategory', 'geometry': '', 'spatialref': '', 'fields': 'makereadycategory.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False, 'gpsmetadata': False}"}
{"asctime": "2020-06-29 06:20:28,788", "levelname": "DEBUG", "message": "ApplyDataModel :Creating table MakeReadyCategory"}
{"asctime": "2020-06-29 06:20:30,524", "levelname": "DEBUG", "message": "ApplyDataModel :MakeReadyCategory created"}
{"asctime": "2020-06-29 06:20:30,526", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/MakeReadyCategory"}
{"asctime": "2020-06-29 06:20:30,527", "levelname": "DEBUG", "message": "ApplyDataModel :Applying MakeReadyCategoryId"}
{"asctime": "2020-06-29 06:20:31,997", "levelname": "DEBUG", "message": "ApplyDataModel :Field MakeReadyCategoryId added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/MakeReadyCategory"}
{"asctime": "2020-06-29 06:20:31,998", "levelname": "DEBUG", "message": "ApplyDataModel :Applying PoleId"}
{"asctime": "2020-06-29 06:20:33,476", "levelname": "DEBUG", "message": "ApplyDataModel :Field PoleId added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/MakeReadyCategory"}
{"asctime": "2020-06-29 06:20:33,476", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Category"}
{"asctime": "2020-06-29 06:20:34,722", "levelname": "DEBUG", "message": "ApplyDataModel :Field Category added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/MakeReadyCategory"}
{"asctime": "2020-06-29 06:20:34,723", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Globals Ids."}
{"asctime": "2020-06-29 06:20:36,429", "levelname": "DEBUG", "message": "ApplyDataModel :Global Ids done."}
{"asctime": "2020-06-29 06:20:36,429", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Editor tracking fields."}
{"asctime": "2020-06-29 06:20:38,274", "levelname": "DEBUG", "message": "ApplyDataModel :Editor tracking enabled."}
{"asctime": "2020-06-29 06:20:38,274", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling archiving."}
{"asctime": "2020-06-29 06:20:38,578", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:20:38,579", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 249, in _manage_database_item\n    arcpy.EnableArchiving_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 209, in EnableArchiving\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 206, in EnableArchiving\n    retval = convertArcObjectToPythonObject(gp.EnableArchiving_management(*gp_fixargs((in_dataset,), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:20:38,580", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'Pole', 'geometry': 'POINT', 'spatialref': 2277, 'fields': 'pole.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': True, 'gpsmetadata': True}"}
{"asctime": "2020-06-29 06:20:38,611", "levelname": "DEBUG", "message": "ApplyDataModel :Creating feature class Pole"}
{"asctime": "2020-06-29 06:20:39,946", "levelname": "DEBUG", "message": "ApplyDataModel :Pole created"}
{"asctime": "2020-06-29 06:20:39,949", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Pole"}
{"asctime": "2020-06-29 06:20:39,949", "levelname": "DEBUG", "message": "ApplyDataModel :Applying PoleId"}
{"asctime": "2020-06-29 06:20:41,003", "levelname": "DEBUG", "message": "ApplyDataModel :Field PoleId added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Pole"}
{"asctime": "2020-06-29 06:20:41,003", "levelname": "DEBUG", "message": "ApplyDataModel :Applying PoleNumber"}
{"asctime": "2020-06-29 06:20:42,127", "levelname": "DEBUG", "message": "ApplyDataModel :Field PoleNumber added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Pole"}
{"asctime": "2020-06-29 06:20:42,128", "levelname": "DEBUG", "message": "ApplyDataModel :Applying ExtensionArm"}
{"asctime": "2020-06-29 06:20:43,523", "levelname": "DEBUG", "message": "ApplyDataModel :Field ExtensionArm added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Pole"}
{"asctime": "2020-06-29 06:20:43,524", "levelname": "DEBUG", "message": "ApplyDataModel :Applying ProposedAttachmentHeight"}
{"asctime": "2020-06-29 06:20:45,010", "levelname": "DEBUG", "message": "ApplyDataModel :Field ProposedAttachmentHeight added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Pole"}
{"asctime": "2020-06-29 06:20:45,010", "levelname": "DEBUG", "message": "ApplyDataModel :Applying CollectionComplete"}
{"asctime": "2020-06-29 06:20:46,949", "levelname": "DEBUG", "message": "ApplyDataModel :Field CollectionComplete added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Pole"}
{"asctime": "2020-06-29 06:20:46,949", "levelname": "DEBUG", "message": "ApplyDataModel :Applying FromCableId"}
{"asctime": "2020-06-29 06:20:48,600", "levelname": "DEBUG", "message": "ApplyDataModel :Field FromCableId added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Pole"}
{"asctime": "2020-06-29 06:20:48,600", "levelname": "DEBUG", "message": "ApplyDataModel :Applying ToCableId"}
{"asctime": "2020-06-29 06:20:49,918", "levelname": "DEBUG", "message": "ApplyDataModel :Field ToCableId added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/Pole"}
{"asctime": "2020-06-29 06:20:49,918", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Globals Ids."}
{"asctime": "2020-06-29 06:20:51,447", "levelname": "DEBUG", "message": "ApplyDataModel :Global Ids done."}
{"asctime": "2020-06-29 06:20:51,448", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Editor tracking fields."}
{"asctime": "2020-06-29 06:20:53,224", "levelname": "DEBUG", "message": "ApplyDataModel :Editor tracking enabled."}
{"asctime": "2020-06-29 06:20:53,224", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling archiving."}
{"asctime": "2020-06-29 06:20:53,494", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:20:53,495", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 249, in _manage_database_item\n    arcpy.EnableArchiving_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 209, in EnableArchiving\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 206, in EnableArchiving\n    retval = convertArcObjectToPythonObject(gp.EnableArchiving_management(*gp_fixargs((in_dataset,), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:20:53,496", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling attachments."}
{"asctime": "2020-06-29 06:20:54,987", "levelname": "DEBUG", "message": "ApplyDataModel :Attachments enabled."}
{"asctime": "2020-06-29 06:20:54,987", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling GPS metadata."}
{"asctime": "2020-06-29 06:21:29,904", "levelname": "DEBUG", "message": "ApplyDataModel :GPS metadata enabled."}
{"asctime": "2020-06-29 06:21:29,904", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'RedlineChangeArea', 'geometry': 'POLYGON', 'spatialref': 2277, 'fields': 'redlinechangearea.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False, 'gpsmetadata': False}"}
{"asctime": "2020-06-29 06:21:29,933", "levelname": "DEBUG", "message": "ApplyDataModel :Creating feature class RedlineChangeArea"}
{"asctime": "2020-06-29 06:21:31,409", "levelname": "DEBUG", "message": "ApplyDataModel :RedlineChangeArea created"}
{"asctime": "2020-06-29 06:21:31,412", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/RedlineChangeArea"}
{"asctime": "2020-06-29 06:21:31,412", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Description"}
{"asctime": "2020-06-29 06:21:33,076", "levelname": "DEBUG", "message": "ApplyDataModel :Field Description added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/RedlineChangeArea"}
{"asctime": "2020-06-29 06:21:33,076", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Comment"}
{"asctime": "2020-06-29 06:21:34,708", "levelname": "DEBUG", "message": "ApplyDataModel :Field Comment added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/RedlineChangeArea"}
{"asctime": "2020-06-29 06:21:34,709", "levelname": "DEBUG", "message": "ApplyDataModel :Applying ApprovalStatus"}
{"asctime": "2020-06-29 06:21:36,478", "levelname": "DEBUG", "message": "ApplyDataModel :Field ApprovalStatus added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/RedlineChangeArea"}
{"asctime": "2020-06-29 06:21:36,479", "levelname": "DEBUG", "message": "ApplyDataModel :Applying ChangeId"}
{"asctime": "2020-06-29 06:21:37,964", "levelname": "DEBUG", "message": "ApplyDataModel :Field ChangeId added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/RedlineChangeArea"}
{"asctime": "2020-06-29 06:21:37,965", "levelname": "DEBUG", "message": "ApplyDataModel :Applying RedlineFeatureId"}
{"asctime": "2020-06-29 06:21:39,389", "levelname": "DEBUG", "message": "ApplyDataModel :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/RedlineChangeArea"}
{"asctime": "2020-06-29 06:21:39,390", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Globals Ids."}
{"asctime": "2020-06-29 06:21:40,911", "levelname": "DEBUG", "message": "ApplyDataModel :Global Ids done."}
{"asctime": "2020-06-29 06:21:40,911", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Editor tracking fields."}
{"asctime": "2020-06-29 06:21:42,751", "levelname": "DEBUG", "message": "ApplyDataModel :Editor tracking enabled."}
{"asctime": "2020-06-29 06:21:42,751", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling archiving."}
{"asctime": "2020-06-29 06:21:43,037", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:21:43,038", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 249, in _manage_database_item\n    arcpy.EnableArchiving_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 209, in EnableArchiving\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 206, in EnableArchiving\n    retval = convertArcObjectToPythonObject(gp.EnableArchiving_management(*gp_fixargs((in_dataset,), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:21:43,039", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'RedlinePointMarker', 'geometry': 'POINT', 'spatialref': 2277, 'fields': 'redlinepointmarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': True, 'gpsmetadata': False}"}
{"asctime": "2020-06-29 06:21:43,065", "levelname": "DEBUG", "message": "ApplyDataModel :Creating feature class RedlinePointMarker"}
{"asctime": "2020-06-29 06:21:44,328", "levelname": "DEBUG", "message": "ApplyDataModel :RedlinePointMarker created"}
{"asctime": "2020-06-29 06:21:44,330", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/RedlinePointMarker"}
{"asctime": "2020-06-29 06:21:44,331", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Label"}
{"asctime": "2020-06-29 06:21:45,434", "levelname": "DEBUG", "message": "ApplyDataModel :Field Label added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/RedlinePointMarker"}
{"asctime": "2020-06-29 06:21:45,434", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Comment"}
{"asctime": "2020-06-29 06:21:46,537", "levelname": "DEBUG", "message": "ApplyDataModel :Field Comment added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/RedlinePointMarker"}
{"asctime": "2020-06-29 06:21:46,537", "levelname": "DEBUG", "message": "ApplyDataModel :Applying RedlineFeatureId"}
{"asctime": "2020-06-29 06:21:47,906", "levelname": "DEBUG", "message": "ApplyDataModel :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/RedlinePointMarker"}
{"asctime": "2020-06-29 06:21:47,907", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Globals Ids."}
{"asctime": "2020-06-29 06:21:49,717", "levelname": "DEBUG", "message": "ApplyDataModel :Global Ids done."}
{"asctime": "2020-06-29 06:21:49,718", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Editor tracking fields."}
{"asctime": "2020-06-29 06:21:51,658", "levelname": "DEBUG", "message": "ApplyDataModel :Editor tracking enabled."}
{"asctime": "2020-06-29 06:21:51,659", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling archiving."}
{"asctime": "2020-06-29 06:21:51,923", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:21:51,923", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 249, in _manage_database_item\n    arcpy.EnableArchiving_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 209, in EnableArchiving\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 206, in EnableArchiving\n    retval = convertArcObjectToPythonObject(gp.EnableArchiving_management(*gp_fixargs((in_dataset,), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:21:51,924", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling attachments."}
{"asctime": "2020-06-29 06:21:53,259", "levelname": "DEBUG", "message": "ApplyDataModel :Attachments enabled."}
{"asctime": "2020-06-29 06:21:53,260", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'RedlineLineMarker', 'geometry': 'POLYLINE', 'spatialref': 2277, 'fields': 'redlinelinemarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False, 'gpsmetadata': False}"}
{"asctime": "2020-06-29 06:21:53,286", "levelname": "DEBUG", "message": "ApplyDataModel :Creating feature class RedlineLineMarker"}
{"asctime": "2020-06-29 06:21:54,531", "levelname": "DEBUG", "message": "ApplyDataModel :RedlineLineMarker created"}
{"asctime": "2020-06-29 06:21:54,533", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/RedlineLineMarker"}
{"asctime": "2020-06-29 06:21:54,534", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Label"}
{"asctime": "2020-06-29 06:21:55,562", "levelname": "DEBUG", "message": "ApplyDataModel :Field Label added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/RedlineLineMarker"}
{"asctime": "2020-06-29 06:21:55,563", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Comment"}
{"asctime": "2020-06-29 06:21:56,649", "levelname": "DEBUG", "message": "ApplyDataModel :Field Comment added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/RedlineLineMarker"}
{"asctime": "2020-06-29 06:21:56,649", "levelname": "DEBUG", "message": "ApplyDataModel :Applying RedlineFeatureId"}
{"asctime": "2020-06-29 06:21:57,740", "levelname": "DEBUG", "message": "ApplyDataModel :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/RedlineLineMarker"}
{"asctime": "2020-06-29 06:21:57,740", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Globals Ids."}
{"asctime": "2020-06-29 06:21:59,156", "levelname": "DEBUG", "message": "ApplyDataModel :Global Ids done."}
{"asctime": "2020-06-29 06:21:59,156", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Editor tracking fields."}
{"asctime": "2020-06-29 06:22:01,346", "levelname": "DEBUG", "message": "ApplyDataModel :Editor tracking enabled."}
{"asctime": "2020-06-29 06:22:01,346", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling archiving."}
{"asctime": "2020-06-29 06:22:01,648", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:22:01,649", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 249, in _manage_database_item\n    arcpy.EnableArchiving_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 209, in EnableArchiving\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 206, in EnableArchiving\n    retval = convertArcObjectToPythonObject(gp.EnableArchiving_management(*gp_fixargs((in_dataset,), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:22:01,649", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'RedlineComment', 'geometry': '', 'spatialref': '', 'fields': 'redlinecomment.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False, 'gpsmetadata': False}"}
{"asctime": "2020-06-29 06:22:01,677", "levelname": "DEBUG", "message": "ApplyDataModel :Creating table RedlineComment"}
{"asctime": "2020-06-29 06:22:03,050", "levelname": "DEBUG", "message": "ApplyDataModel :RedlineComment created"}
{"asctime": "2020-06-29 06:22:03,051", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/RedlineComment"}
{"asctime": "2020-06-29 06:22:03,052", "levelname": "DEBUG", "message": "ApplyDataModel :Applying ApprovalStatus"}
{"asctime": "2020-06-29 06:22:04,091", "levelname": "DEBUG", "message": "ApplyDataModel :Field ApprovalStatus added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/RedlineComment"}
{"asctime": "2020-06-29 06:22:04,091", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Comment"}
{"asctime": "2020-06-29 06:22:05,147", "levelname": "DEBUG", "message": "ApplyDataModel :Field Comment added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/RedlineComment"}
{"asctime": "2020-06-29 06:22:05,147", "levelname": "DEBUG", "message": "ApplyDataModel :Applying RedlineFeatureId"}
{"asctime": "2020-06-29 06:22:06,138", "levelname": "DEBUG", "message": "ApplyDataModel :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/RedlineComment"}
{"asctime": "2020-06-29 06:22:06,139", "levelname": "DEBUG", "message": "ApplyDataModel :Applying RedlineCommentId"}
{"asctime": "2020-06-29 06:22:07,282", "levelname": "DEBUG", "message": "ApplyDataModel :Field RedlineCommentId added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/RedlineComment"}
{"asctime": "2020-06-29 06:22:07,282", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Globals Ids."}
{"asctime": "2020-06-29 06:22:08,889", "levelname": "DEBUG", "message": "ApplyDataModel :Global Ids done."}
{"asctime": "2020-06-29 06:22:08,890", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Editor tracking fields."}
{"asctime": "2020-06-29 06:22:10,545", "levelname": "DEBUG", "message": "ApplyDataModel :Editor tracking enabled."}
{"asctime": "2020-06-29 06:22:10,546", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling archiving."}
{"asctime": "2020-06-29 06:22:10,857", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:22:10,857", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 249, in _manage_database_item\n    arcpy.EnableArchiving_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 209, in EnableArchiving\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 206, in EnableArchiving\n    retval = convertArcObjectToPythonObject(gp.EnableArchiving_management(*gp_fixargs((in_dataset,), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:22:10,858", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'ServicePoint', 'geometry': 'POINT', 'spatialref': 2231, 'fields': 'servicepoint.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False, 'gpsmetadata': True}"}
{"asctime": "2020-06-29 06:22:10,883", "levelname": "DEBUG", "message": "ApplyDataModel :Creating feature class ServicePoint"}
{"asctime": "2020-06-29 06:22:12,384", "levelname": "DEBUG", "message": "ApplyDataModel :ServicePoint created"}
{"asctime": "2020-06-29 06:22:12,387", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/ServicePoint"}
{"asctime": "2020-06-29 06:22:12,388", "levelname": "DEBUG", "message": "ApplyDataModel :Applying ServicePointId"}
{"asctime": "2020-06-29 06:22:13,993", "levelname": "DEBUG", "message": "ApplyDataModel :Field ServicePointId added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/ServicePoint"}
{"asctime": "2020-06-29 06:22:13,994", "levelname": "DEBUG", "message": "ApplyDataModel :Applying CustomerNumber"}
{"asctime": "2020-06-29 06:22:15,496", "levelname": "DEBUG", "message": "ApplyDataModel :Field CustomerNumber added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/ServicePoint"}
{"asctime": "2020-06-29 06:22:15,497", "levelname": "DEBUG", "message": "ApplyDataModel :Applying CustomerServicePointId"}
{"asctime": "2020-06-29 06:22:16,962", "levelname": "DEBUG", "message": "ApplyDataModel :Field CustomerServicePointId added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/ServicePoint"}
{"asctime": "2020-06-29 06:22:16,962", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Name"}
{"asctime": "2020-06-29 06:22:18,485", "levelname": "DEBUG", "message": "ApplyDataModel :Field Name added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/ServicePoint"}
{"asctime": "2020-06-29 06:22:18,486", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Address"}
{"asctime": "2020-06-29 06:22:19,773", "levelname": "DEBUG", "message": "ApplyDataModel :Field Address added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/ServicePoint"}
{"asctime": "2020-06-29 06:22:19,774", "levelname": "DEBUG", "message": "ApplyDataModel :Applying City"}
{"asctime": "2020-06-29 06:22:20,905", "levelname": "DEBUG", "message": "ApplyDataModel :Field City added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/ServicePoint"}
{"asctime": "2020-06-29 06:22:20,905", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Multiple"}
{"asctime": "2020-06-29 06:22:21,952", "levelname": "DEBUG", "message": "ApplyDataModel :Field Multiple added to C:/Cloud/Dropbox/Work/Axin/RDTDataModel/20200629/rdtfielding.gdb/ServicePoint"}
{"asctime": "2020-06-29 06:22:21,953", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Globals Ids."}
{"asctime": "2020-06-29 06:22:23,277", "levelname": "DEBUG", "message": "ApplyDataModel :Global Ids done."}
{"asctime": "2020-06-29 06:22:23,278", "levelname": "DEBUG", "message": "ApplyDataModel :Adding Editor tracking fields."}
{"asctime": "2020-06-29 06:22:24,862", "levelname": "DEBUG", "message": "ApplyDataModel :Editor tracking enabled."}
{"asctime": "2020-06-29 06:22:24,862", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling archiving."}
{"asctime": "2020-06-29 06:22:25,172", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:22:25,172", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Cloud\\Dropbox\\Work\\Axin\\Python\\ApplyDataModel\\ApplyDataModel.py\", line 249, in _manage_database_item\n    arcpy.EnableArchiving_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 209, in EnableArchiving\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 206, in EnableArchiving\n    retval = convertArcObjectToPythonObject(gp.EnableArchiving_management(*gp_fixargs((in_dataset,), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 001542: This dataset type is not supported by archiving.\nFailed to execute (EnableArchiving).\n"}
{"asctime": "2020-06-29 06:22:25,173", "levelname": "DEBUG", "message": "ApplyDataModel :Enabling GPS metadata."}
{"asctime": "2020-06-29 06:22:57,694", "levelname": "DEBUG", "message": "ApplyDataModel :GPS metadata enabled."}
{"asctime": "2020-06-29 06:22:57,694", "levelname": "DEBUG", "message": "ApplyDataModel :Processing feature classes finished."}
