{"asctime": "2020-03-26 13:59:32,815", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000356: Invalid domain type.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:59:32,831", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 13:59:33,208", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 13:59:33,209", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:59:33,209", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:59:33,211", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 13:59:34,783", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 13:59:34,784", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlinePointMarker', 'geometry': 'POINT', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinepointmarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': True}"}
{"asctime": "2020-03-26 13:59:34,947", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlinePointMarker exists."}
{"asctime": "2020-03-26 13:59:34,947", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 13:59:36,210", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class RedlinePointMarker"}
{"asctime": "2020-03-26 13:59:37,959", "levelname": "DEBUG", "message": "CreateFeatureClass :RedlinePointMarker created"}
{"asctime": "2020-03-26 13:59:37,960", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 13:59:37,961", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Label"}
{"asctime": "2020-03-26 13:59:39,512", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Label added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 13:59:39,513", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comments"}
{"asctime": "2020-03-26 13:59:41,058", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Comments added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 13:59:41,058", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 13:59:41,478", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 13:59:41,478", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:59:41,479", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:59:41,481", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 13:59:43,314", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 13:59:43,314", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineLineMarker', 'geometry': 'POLYLINE', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinelinemarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 13:59:43,522", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlineLineMarker exists."}
{"asctime": "2020-03-26 13:59:43,523", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 13:59:45,177", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class RedlineLineMarker"}
{"asctime": "2020-03-26 13:59:47,602", "levelname": "DEBUG", "message": "CreateFeatureClass :RedlineLineMarker created"}
{"asctime": "2020-03-26 13:59:47,603", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 13:59:47,604", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Label"}
{"asctime": "2020-03-26 13:59:49,582", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Label added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 13:59:49,583", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comments"}
{"asctime": "2020-03-26 13:59:51,503", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Comments added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 13:59:51,504", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 13:59:51,972", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 13:59:51,972", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:59:51,973", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:59:51,975", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 13:59:53,891", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 13:59:53,891", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineComment', 'geometry': '', 'spatialref': '', 'fields': 'redlinecomment.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 13:59:54,124", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlineComment exists."}
{"asctime": "2020-03-26 13:59:54,125", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 13:59:55,485", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating table RedlineComment"}
{"asctime": "2020-03-26 13:59:57,888", "levelname": "DEBUG", "message": "CreateFeatureClass :RedlineComment created"}
{"asctime": "2020-03-26 13:59:57,889", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 13:59:57,891", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying ApprovalStatus"}
{"asctime": "2020-03-26 13:59:59,607", "levelname": "DEBUG", "message": "CreateFeatureClass :Field ApprovalStatus added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 13:59:59,609", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comment"}
{"asctime": "2020-03-26 14:00:01,440", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Comment added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 14:00:01,441", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 14:00:01,872", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 14:00:01,872", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:00:01,872", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:00:01,874", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 14:00:03,506", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 14:00:03,507", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineCommentId"}
{"asctime": "2020-03-26 14:00:04,947", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineCommentId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 14:00:04,948", "levelname": "DEBUG", "message": "CreateFeatureClass :Processing feature classes finished."}
{"asctime": "2020-03-26 14:00:34,433", "levelname": "DEBUG", "message": "CreateFeatureClass :Class:CreateFeatureClass"}
{"asctime": "2020-03-26 14:00:34,436", "levelname": "DEBUG", "message": "CreateFeatureClass :loaded config for CreateFeatureClass from c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.json"}
{"asctime": "2020-03-26 14:00:34,436", "levelname": "DEBUG", "message": "CreateFeatureClass :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas"}
{"asctime": "2020-03-26 14:00:34,436", "levelname": "DEBUG", "message": "CreateFeatureClass :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas/prjs/prjs.gdb"}
{"asctime": "2020-03-26 14:00:37,816", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't create domain ApprovalStatus"}
{"asctime": "2020-03-26 14:00:37,817", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 14:00:37,817", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 14:00:42,838", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineChangeArea', 'geometry': 'POLYGON', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinechangearea.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 14:00:43,080", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlineChangeArea exists."}
{"asctime": "2020-03-26 14:00:43,081", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 14:00:44,720", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class RedlineChangeArea"}
{"asctime": "2020-03-26 14:00:47,148", "levelname": "DEBUG", "message": "CreateFeatureClass :RedlineChangeArea created"}
{"asctime": "2020-03-26 14:00:47,149", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 14:00:47,150", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Description"}
{"asctime": "2020-03-26 14:00:49,129", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Description added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 14:00:49,129", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comments"}
{"asctime": "2020-03-26 14:00:51,362", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Comments added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 14:00:51,362", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying ApprovalStatus"}
{"asctime": "2020-03-26 14:00:53,643", "levelname": "DEBUG", "message": "CreateFeatureClass :Field ApprovalStatus added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 14:00:53,643", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying ChangeId"}
{"asctime": "2020-03-26 14:00:55,612", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field ChangeId failed"}
{"asctime": "2020-03-26 14:00:55,613", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000356: Invalid domain type.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:00:55,614", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000356: Invalid domain type.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:00:55,617", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 14:00:56,110", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 14:00:56,110", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:00:56,111", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:00:56,113", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 14:00:58,239", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 14:00:58,240", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlinePointMarker', 'geometry': 'POINT', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinepointmarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': True}"}
{"asctime": "2020-03-26 14:00:58,449", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlinePointMarker exists."}
{"asctime": "2020-03-26 14:00:58,450", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 14:00:59,786", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class RedlinePointMarker"}
{"asctime": "2020-03-26 14:01:01,544", "levelname": "DEBUG", "message": "CreateFeatureClass :RedlinePointMarker created"}
{"asctime": "2020-03-26 14:01:01,544", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 14:01:01,545", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Label"}
{"asctime": "2020-03-26 14:01:03,030", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Label added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 14:01:03,031", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comments"}
{"asctime": "2020-03-26 14:01:04,527", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Comments added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 14:01:04,527", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 14:01:04,919", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 14:01:04,920", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:01:04,920", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:01:04,923", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 14:01:06,442", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 14:01:06,442", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineLineMarker', 'geometry': 'POLYLINE', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinelinemarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 14:01:06,602", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlineLineMarker exists."}
{"asctime": "2020-03-26 14:01:06,603", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 14:01:07,883", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class RedlineLineMarker"}
{"asctime": "2020-03-26 14:01:10,223", "levelname": "DEBUG", "message": "CreateFeatureClass :RedlineLineMarker created"}
{"asctime": "2020-03-26 14:01:10,224", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 14:01:10,224", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Label"}
{"asctime": "2020-03-26 14:01:12,270", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Label added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 14:01:12,271", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comments"}
{"asctime": "2020-03-26 14:01:14,266", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Comments added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 14:01:14,266", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 14:01:14,757", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 14:01:14,758", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:01:14,758", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:01:14,761", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 14:01:16,728", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 14:01:16,729", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineComment', 'geometry': '', 'spatialref': '', 'fields': 'redlinecomment.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 14:01:16,988", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlineComment exists."}
{"asctime": "2020-03-26 14:01:16,989", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 14:01:18,485", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating table RedlineComment"}
{"asctime": "2020-03-26 14:01:20,934", "levelname": "DEBUG", "message": "CreateFeatureClass :RedlineComment created"}
{"asctime": "2020-03-26 14:01:20,935", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 14:01:20,936", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying ApprovalStatus"}
{"asctime": "2020-03-26 14:01:22,814", "levelname": "DEBUG", "message": "CreateFeatureClass :Field ApprovalStatus added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 14:01:22,814", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comment"}
{"asctime": "2020-03-26 14:01:24,587", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Comment added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 14:01:24,588", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 14:01:25,005", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 14:01:25,005", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:01:25,006", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:01:25,007", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 14:01:26,543", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 14:01:26,543", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineCommentId"}
{"asctime": "2020-03-26 14:01:27,932", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineCommentId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 14:01:27,932", "levelname": "DEBUG", "message": "CreateFeatureClass :Processing feature classes finished."}
{"asctime": "2020-03-26 14:12:10,042", "levelname": "DEBUG", "message": "CreateFeatureClass :Class:CreateFeatureClass"}
{"asctime": "2020-03-26 14:12:10,045", "levelname": "DEBUG", "message": "CreateFeatureClass :loaded config for CreateFeatureClass from c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.json"}
{"asctime": "2020-03-26 14:12:10,045", "levelname": "DEBUG", "message": "CreateFeatureClass :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas"}
{"asctime": "2020-03-26 14:12:10,046", "levelname": "DEBUG", "message": "CreateFeatureClass :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas/prjs/prjs.gdb"}
{"asctime": "2020-03-26 14:12:14,416", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't create domain ApprovalStatus"}
{"asctime": "2020-03-26 14:12:14,417", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 14:12:14,417", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 14:12:19,146", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineChangeArea', 'geometry': 'POLYGON', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinechangearea.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 14:12:19,424", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class RedlineChangeArea"}
{"asctime": "2020-03-26 14:12:21,648", "levelname": "DEBUG", "message": "CreateFeatureClass :RedlineChangeArea created"}
{"asctime": "2020-03-26 14:12:21,650", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 14:12:21,651", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Description"}
{"asctime": "2020-03-26 14:12:23,330", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field Description failed"}
{"asctime": "2020-03-26 14:12:23,331", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:23,331", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:23,334", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comments"}
{"asctime": "2020-03-26 14:12:24,845", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field Comments failed"}
{"asctime": "2020-03-26 14:12:24,846", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:24,846", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:24,848", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying ApprovalStatus"}
{"asctime": "2020-03-26 14:12:26,342", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field ApprovalStatus failed"}
{"asctime": "2020-03-26 14:12:26,342", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:26,343", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:26,344", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying ChangeId"}
{"asctime": "2020-03-26 14:12:27,770", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field ChangeId failed"}
{"asctime": "2020-03-26 14:12:27,771", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:27,771", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:27,772", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 14:12:28,133", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 14:12:28,134", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:28,134", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:28,136", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 14:12:29,504", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field RedlineFeatureId failed"}
{"asctime": "2020-03-26 14:12:29,504", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:29,505", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:29,507", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlinePointMarker', 'geometry': 'POINT', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinepointmarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': True}"}
{"asctime": "2020-03-26 14:12:29,702", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class RedlinePointMarker"}
{"asctime": "2020-03-26 14:12:31,612", "levelname": "DEBUG", "message": "CreateFeatureClass :RedlinePointMarker created"}
{"asctime": "2020-03-26 14:12:31,613", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 14:12:31,614", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Label"}
{"asctime": "2020-03-26 14:12:32,922", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field Label failed"}
{"asctime": "2020-03-26 14:12:32,922", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:32,923", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:32,924", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comments"}
{"asctime": "2020-03-26 14:12:34,163", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field Comments failed"}
{"asctime": "2020-03-26 14:12:34,164", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:34,164", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:34,165", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 14:12:34,549", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 14:12:34,550", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:34,550", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:34,552", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 14:12:35,957", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field RedlineFeatureId failed"}
{"asctime": "2020-03-26 14:12:35,958", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:35,958", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:35,960", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineLineMarker', 'geometry': 'POLYLINE', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinelinemarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 14:12:36,178", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class RedlineLineMarker"}
{"asctime": "2020-03-26 14:12:38,076", "levelname": "DEBUG", "message": "CreateFeatureClass :RedlineLineMarker created"}
{"asctime": "2020-03-26 14:12:38,077", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 14:12:38,078", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Label"}
{"asctime": "2020-03-26 14:12:39,482", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field Label failed"}
{"asctime": "2020-03-26 14:12:39,483", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:39,483", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:39,485", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comments"}
{"asctime": "2020-03-26 14:12:41,028", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field Comments failed"}
{"asctime": "2020-03-26 14:12:41,028", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:41,029", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:41,031", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 14:12:41,440", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 14:12:41,441", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:41,441", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:41,443", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 14:12:42,920", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field RedlineFeatureId failed"}
{"asctime": "2020-03-26 14:12:42,920", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:42,921", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:42,922", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineComment', 'geometry': '', 'spatialref': '', 'fields': 'redlinecomment.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 14:12:42,962", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating table RedlineComment"}
{"asctime": "2020-03-26 14:12:44,996", "levelname": "DEBUG", "message": "CreateFeatureClass :RedlineComment created"}
{"asctime": "2020-03-26 14:12:44,997", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 14:12:44,999", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying ApprovalStatus"}
{"asctime": "2020-03-26 14:12:46,209", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field ApprovalStatus failed"}
{"asctime": "2020-03-26 14:12:46,209", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:46,210", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:46,211", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comment"}
{"asctime": "2020-03-26 14:12:47,411", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field Comment failed"}
{"asctime": "2020-03-26 14:12:47,412", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:47,412", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:47,413", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 14:12:47,769", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 14:12:47,769", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:47,770", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:47,771", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 14:12:48,786", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field RedlineFeatureId failed"}
{"asctime": "2020-03-26 14:12:48,787", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:48,787", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:48,789", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineCommentId"}
{"asctime": "2020-03-26 14:12:49,878", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field RedlineCommentId failed"}
{"asctime": "2020-03-26 14:12:49,878", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:49,878", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:12:49,880", "levelname": "DEBUG", "message": "CreateFeatureClass :Processing feature classes finished."}
{"asctime": "2020-03-26 14:12:50,377", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't add relationship for to RedlineChangeArea_RedlineComment"}
{"asctime": "2020-03-26 14:13:18,216", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000800: The value is not a member of OBJECTID | Shape_Area | Shape_Length.\nERROR 000800: The value is not a member of OBJECTID.\nFailed to execute (CreateRelationshipClass).\n"}
{"asctime": "2020-03-26 14:13:18,217", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 88, in _process_relationship_classes\n    arcpy.CreateRelationshipClass_management(f\"{self._connection}/{a_relationship['origin']}\",f\"{self._connection}/{a_relationship['destination']}\", a_relationship['outclass'], a_relationship['type'], a_relationship['forwardlabel'], a_relationship['backlabel'], a_relationship['message'], a_relationship['cardinality'], a_relationship['attributed'], a_relationship['originpk'], a_relationship['originfk'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19096, in CreateRelationshipClass\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19093, in CreateRelationshipClass\n    retval = convertArcObjectToPythonObject(gp.CreateRelationshipClass_management(*gp_fixargs((origin_table, destination_table, out_relationship_class, relationship_type, forward_label, backward_label, message_direction, cardinality, attributed, origin_primary_key, origin_foreign_key, destination_primary_key, destination_foreign_key), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000800: The value is not a member of OBJECTID | Shape_Area | Shape_Length.\nERROR 000800: The value is not a member of OBJECTID.\nFailed to execute (CreateRelationshipClass).\n"}
{"asctime": "2020-03-26 14:13:58,624", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't add relationship for to RedlinePointMarker_RedlineComment"}
{"asctime": "2020-03-26 14:14:00,427", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000800: The value is not a member of OBJECTID.\nERROR 000800: The value is not a member of OBJECTID.\nFailed to execute (CreateRelationshipClass).\n"}
{"asctime": "2020-03-26 14:14:00,428", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 88, in _process_relationship_classes\n    arcpy.CreateRelationshipClass_management(f\"{self._connection}/{a_relationship['origin']}\",f\"{self._connection}/{a_relationship['destination']}\", a_relationship['outclass'], a_relationship['type'], a_relationship['forwardlabel'], a_relationship['backlabel'], a_relationship['message'], a_relationship['cardinality'], a_relationship['attributed'], a_relationship['originpk'], a_relationship['originfk'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19096, in CreateRelationshipClass\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19093, in CreateRelationshipClass\n    retval = convertArcObjectToPythonObject(gp.CreateRelationshipClass_management(*gp_fixargs((origin_table, destination_table, out_relationship_class, relationship_type, forward_label, backward_label, message_direction, cardinality, attributed, origin_primary_key, origin_foreign_key, destination_primary_key, destination_foreign_key), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000800: The value is not a member of OBJECTID.\nERROR 000800: The value is not a member of OBJECTID.\nFailed to execute (CreateRelationshipClass).\n"}
{"asctime": "2020-03-26 14:14:01,733", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't add relationship for to RedlineLineMarker_RedlineComment"}
{"asctime": "2020-03-26 14:14:02,452", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000800: The value is not a member of OBJECTID | Shape_Length.\nERROR 000800: The value is not a member of OBJECTID.\nFailed to execute (CreateRelationshipClass).\n"}
{"asctime": "2020-03-26 14:14:02,453", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 88, in _process_relationship_classes\n    arcpy.CreateRelationshipClass_management(f\"{self._connection}/{a_relationship['origin']}\",f\"{self._connection}/{a_relationship['destination']}\", a_relationship['outclass'], a_relationship['type'], a_relationship['forwardlabel'], a_relationship['backlabel'], a_relationship['message'], a_relationship['cardinality'], a_relationship['attributed'], a_relationship['originpk'], a_relationship['originfk'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19096, in CreateRelationshipClass\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19093, in CreateRelationshipClass\n    retval = convertArcObjectToPythonObject(gp.CreateRelationshipClass_management(*gp_fixargs((origin_table, destination_table, out_relationship_class, relationship_type, forward_label, backward_label, message_direction, cardinality, attributed, origin_primary_key, origin_foreign_key, destination_primary_key, destination_foreign_key), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000800: The value is not a member of OBJECTID | Shape_Length.\nERROR 000800: The value is not a member of OBJECTID.\nFailed to execute (CreateRelationshipClass).\n"}
{"asctime": "2020-03-26 14:14:50,841", "levelname": "DEBUG", "message": "CreateFeatureClass :Class:CreateFeatureClass"}
{"asctime": "2020-03-26 14:14:50,845", "levelname": "DEBUG", "message": "CreateFeatureClass :loaded config for CreateFeatureClass from c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.json"}
{"asctime": "2020-03-26 14:14:50,845", "levelname": "DEBUG", "message": "CreateFeatureClass :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas"}
{"asctime": "2020-03-26 14:14:50,845", "levelname": "DEBUG", "message": "CreateFeatureClass :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas/prjs/prjs.gdb"}
{"asctime": "2020-03-26 14:14:54,287", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't create domain ApprovalStatus"}
{"asctime": "2020-03-26 14:14:54,288", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 14:14:54,288", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 14:14:59,044", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineChangeArea', 'geometry': 'POLYGON', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinechangearea.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 14:14:59,243", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlineChangeArea exists."}
{"asctime": "2020-03-26 14:14:59,244", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 14:15:00,990", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:15:00,990", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 191, in _create_feature_class\n    arcpy.Delete_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5352, in Delete\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5349, in Delete\n    retval = convertArcObjectToPythonObject(gp.Delete_management(*gp_fixargs((in_data, data_type), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:15:00,993", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlinePointMarker', 'geometry': 'POINT', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinepointmarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': True}"}
{"asctime": "2020-03-26 14:15:01,203", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlinePointMarker exists."}
{"asctime": "2020-03-26 14:15:01,203", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 14:15:03,005", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:15:03,006", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 191, in _create_feature_class\n    arcpy.Delete_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5352, in Delete\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5349, in Delete\n    retval = convertArcObjectToPythonObject(gp.Delete_management(*gp_fixargs((in_data, data_type), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:15:03,008", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineLineMarker', 'geometry': 'POLYLINE', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinelinemarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 14:15:03,218", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlineLineMarker exists."}
{"asctime": "2020-03-26 14:15:03,219", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 14:15:04,818", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:15:04,819", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 191, in _create_feature_class\n    arcpy.Delete_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5352, in Delete\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5349, in Delete\n    retval = convertArcObjectToPythonObject(gp.Delete_management(*gp_fixargs((in_data, data_type), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:15:04,821", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineComment', 'geometry': '', 'spatialref': '', 'fields': 'redlinecomment.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 14:15:04,997", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlineComment exists."}
{"asctime": "2020-03-26 14:15:04,998", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 14:15:06,560", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:15:06,560", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 191, in _create_feature_class\n    arcpy.Delete_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5352, in Delete\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5349, in Delete\n    retval = convertArcObjectToPythonObject(gp.Delete_management(*gp_fixargs((in_data, data_type), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:15:06,561", "levelname": "DEBUG", "message": "CreateFeatureClass :Processing feature classes finished."}
{"asctime": "2020-03-26 14:15:47,840", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't add relationship for to ChangeArea_Comment"}
{"asctime": "2020-03-26 14:18:40,701", "levelname": "DEBUG", "message": "CreateFeatureClass :Class:CreateFeatureClass"}
{"asctime": "2020-03-26 14:18:40,704", "levelname": "DEBUG", "message": "CreateFeatureClass :loaded config for CreateFeatureClass from c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.json"}
{"asctime": "2020-03-26 14:18:40,704", "levelname": "DEBUG", "message": "CreateFeatureClass :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas"}
{"asctime": "2020-03-26 14:18:40,704", "levelname": "DEBUG", "message": "CreateFeatureClass :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas/prjs/prjs.gdb"}
{"asctime": "2020-03-26 14:18:44,713", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't create domain ApprovalStatus"}
{"asctime": "2020-03-26 14:18:44,714", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 14:18:44,715", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 14:18:49,494", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineChangeArea', 'geometry': 'POLYGON', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinechangearea.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 14:18:49,664", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlineChangeArea exists."}
{"asctime": "2020-03-26 14:18:49,664", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 14:18:51,281", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:18:51,282", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 191, in _create_feature_class\n    arcpy.Delete_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5352, in Delete\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5349, in Delete\n    retval = convertArcObjectToPythonObject(gp.Delete_management(*gp_fixargs((in_data, data_type), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:18:51,284", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlinePointMarker', 'geometry': 'POINT', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinepointmarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': True}"}
{"asctime": "2020-03-26 14:18:51,418", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlinePointMarker exists."}
{"asctime": "2020-03-26 14:18:51,419", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 14:18:53,047", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:18:53,048", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 191, in _create_feature_class\n    arcpy.Delete_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5352, in Delete\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5349, in Delete\n    retval = convertArcObjectToPythonObject(gp.Delete_management(*gp_fixargs((in_data, data_type), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:18:53,050", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineLineMarker', 'geometry': 'POLYLINE', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinelinemarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 14:18:53,199", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlineLineMarker exists."}
{"asctime": "2020-03-26 14:18:53,200", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 14:18:54,774", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:18:54,775", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 191, in _create_feature_class\n    arcpy.Delete_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5352, in Delete\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5349, in Delete\n    retval = convertArcObjectToPythonObject(gp.Delete_management(*gp_fixargs((in_data, data_type), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:18:54,778", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineComment', 'geometry': '', 'spatialref': '', 'fields': 'redlinecomment.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 14:18:54,930", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlineComment exists."}
{"asctime": "2020-03-26 14:18:54,931", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 14:18:56,491", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:18:56,492", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 191, in _create_feature_class\n    arcpy.Delete_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5352, in Delete\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5349, in Delete\n    retval = convertArcObjectToPythonObject(gp.Delete_management(*gp_fixargs((in_data, data_type), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:18:56,494", "levelname": "DEBUG", "message": "CreateFeatureClass :Processing feature classes finished."}
{"asctime": "2020-03-26 14:19:27,791", "levelname": "DEBUG", "message": "CreateFeatureClass :Class:CreateFeatureClass"}
{"asctime": "2020-03-26 14:19:27,794", "levelname": "DEBUG", "message": "CreateFeatureClass :loaded config for CreateFeatureClass from c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.json"}
{"asctime": "2020-03-26 14:19:27,794", "levelname": "DEBUG", "message": "CreateFeatureClass :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas"}
