{"asctime": "2020-03-26 13:08:55,779", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 142, in _process_subtypes\n    arcpy.AddSubtype_management(full_fc, code, st_vals[code])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19589, in AddSubtype\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19586, in AddSubtype\n    retval = convertArcObjectToPythonObject(gp.AddSubtype_management(*gp_fixargs((in_table, subtype_code, subtype_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/MarkupPolygon does not exist or is not supported\nFailed to execute (AddSubtype).\n"}
{"asctime": "2020-03-26 13:08:55,902", "levelname": "DEBUG", "message": "CreateFeatureClass :Setting subtype field C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/MarkupLine,Type failed"}
{"asctime": "2020-03-26 13:08:55,903", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/MarkupLine does not exist or is not supported\nFailed to execute (SetSubtypeField).\n"}
{"asctime": "2020-03-26 13:08:55,904", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 136, in _process_subtypes\n    arcpy.SetSubtypeField_management(full_fc, fd)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19657, in SetSubtypeField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19654, in SetSubtypeField\n    retval = convertArcObjectToPythonObject(gp.SetSubtypeField_management(*gp_fixargs((in_table, field, clear_value), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/MarkupLine does not exist or is not supported\nFailed to execute (SetSubtypeField).\n"}
{"asctime": "2020-03-26 13:08:55,995", "levelname": "DEBUG", "message": "CreateFeatureClass :Setting subtype code C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/MarkupLine,Type,0,Default failed"}
{"asctime": "2020-03-26 13:08:55,996", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/MarkupLine does not exist or is not supported\nFailed to execute (AddSubtype).\n"}
{"asctime": "2020-03-26 13:08:55,996", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 142, in _process_subtypes\n    arcpy.AddSubtype_management(full_fc, code, st_vals[code])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19589, in AddSubtype\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19586, in AddSubtype\n    retval = convertArcObjectToPythonObject(gp.AddSubtype_management(*gp_fixargs((in_table, subtype_code, subtype_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/MarkupLine does not exist or is not supported\nFailed to execute (AddSubtype).\n"}
{"asctime": "2020-03-26 13:08:56,085", "levelname": "DEBUG", "message": "CreateFeatureClass :Setting subtype code C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/MarkupLine,Type,1,Splitter Extent failed"}
{"asctime": "2020-03-26 13:08:56,086", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/MarkupLine does not exist or is not supported\nFailed to execute (AddSubtype).\n"}
{"asctime": "2020-03-26 13:08:56,087", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 142, in _process_subtypes\n    arcpy.AddSubtype_management(full_fc, code, st_vals[code])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19589, in AddSubtype\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19586, in AddSubtype\n    retval = convertArcObjectToPythonObject(gp.AddSubtype_management(*gp_fixargs((in_table, subtype_code, subtype_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/MarkupLine does not exist or is not supported\nFailed to execute (AddSubtype).\n"}
{"asctime": "2020-03-26 13:08:56,204", "levelname": "DEBUG", "message": "CreateFeatureClass :Setting subtype field C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/MarkupPoint,Type failed"}
{"asctime": "2020-03-26 13:08:56,205", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/MarkupPoint does not exist or is not supported\nFailed to execute (SetSubtypeField).\n"}
{"asctime": "2020-03-26 13:08:56,205", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 136, in _process_subtypes\n    arcpy.SetSubtypeField_management(full_fc, fd)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19657, in SetSubtypeField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19654, in SetSubtypeField\n    retval = convertArcObjectToPythonObject(gp.SetSubtypeField_management(*gp_fixargs((in_table, field, clear_value), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/MarkupPoint does not exist or is not supported\nFailed to execute (SetSubtypeField).\n"}
{"asctime": "2020-03-26 13:08:56,308", "levelname": "DEBUG", "message": "CreateFeatureClass :Setting subtype code C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/MarkupPoint,Type,0,Default failed"}
{"asctime": "2020-03-26 13:08:56,309", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/MarkupPoint does not exist or is not supported\nFailed to execute (AddSubtype).\n"}
{"asctime": "2020-03-26 13:08:56,309", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 142, in _process_subtypes\n    arcpy.AddSubtype_management(full_fc, code, st_vals[code])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19589, in AddSubtype\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19586, in AddSubtype\n    retval = convertArcObjectToPythonObject(gp.AddSubtype_management(*gp_fixargs((in_table, subtype_code, subtype_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/MarkupPoint does not exist or is not supported\nFailed to execute (AddSubtype).\n"}
{"asctime": "2020-03-26 13:08:56,429", "levelname": "DEBUG", "message": "CreateFeatureClass :Setting subtype field C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure,Type failed"}
{"asctime": "2020-03-26 13:08:56,430", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure does not exist or is not supported\nFailed to execute (SetSubtypeField).\n"}
{"asctime": "2020-03-26 13:08:56,431", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 136, in _process_subtypes\n    arcpy.SetSubtypeField_management(full_fc, fd)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19657, in SetSubtypeField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19654, in SetSubtypeField\n    retval = convertArcObjectToPythonObject(gp.SetSubtypeField_management(*gp_fixargs((in_table, field, clear_value), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure does not exist or is not supported\nFailed to execute (SetSubtypeField).\n"}
{"asctime": "2020-03-26 13:08:56,526", "levelname": "DEBUG", "message": "CreateFeatureClass :Setting subtype code C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure,Type,1,Pedestal failed"}
{"asctime": "2020-03-26 13:08:56,526", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure does not exist or is not supported\nFailed to execute (AddSubtype).\n"}
{"asctime": "2020-03-26 13:08:56,527", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 142, in _process_subtypes\n    arcpy.AddSubtype_management(full_fc, code, st_vals[code])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19589, in AddSubtype\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19586, in AddSubtype\n    retval = convertArcObjectToPythonObject(gp.AddSubtype_management(*gp_fixargs((in_table, subtype_code, subtype_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure does not exist or is not supported\nFailed to execute (AddSubtype).\n"}
{"asctime": "2020-03-26 13:08:56,619", "levelname": "DEBUG", "message": "CreateFeatureClass :Setting subtype code C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure,Type,3,Handhole failed"}
{"asctime": "2020-03-26 13:08:56,620", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure does not exist or is not supported\nFailed to execute (AddSubtype).\n"}
{"asctime": "2020-03-26 13:08:56,620", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 142, in _process_subtypes\n    arcpy.AddSubtype_management(full_fc, code, st_vals[code])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19589, in AddSubtype\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19586, in AddSubtype\n    retval = convertArcObjectToPythonObject(gp.AddSubtype_management(*gp_fixargs((in_table, subtype_code, subtype_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure does not exist or is not supported\nFailed to execute (AddSubtype).\n"}
{"asctime": "2020-03-26 13:08:56,715", "levelname": "DEBUG", "message": "CreateFeatureClass :Setting subtype code C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure,Type,11,Spice Enclosure failed"}
{"asctime": "2020-03-26 13:08:56,715", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure does not exist or is not supported\nFailed to execute (AddSubtype).\n"}
{"asctime": "2020-03-26 13:08:56,716", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 142, in _process_subtypes\n    arcpy.AddSubtype_management(full_fc, code, st_vals[code])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19589, in AddSubtype\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19586, in AddSubtype\n    retval = convertArcObjectToPythonObject(gp.AddSubtype_management(*gp_fixargs((in_table, subtype_code, subtype_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure does not exist or is not supported\nFailed to execute (AddSubtype).\n"}
{"asctime": "2020-03-26 13:08:56,806", "levelname": "DEBUG", "message": "CreateFeatureClass :Setting subtype code C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure,Type,12,Cabinet failed"}
{"asctime": "2020-03-26 13:08:56,807", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure does not exist or is not supported\nFailed to execute (AddSubtype).\n"}
{"asctime": "2020-03-26 13:08:56,807", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 142, in _process_subtypes\n    arcpy.AddSubtype_management(full_fc, code, st_vals[code])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19589, in AddSubtype\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19586, in AddSubtype\n    retval = convertArcObjectToPythonObject(gp.AddSubtype_management(*gp_fixargs((in_table, subtype_code, subtype_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure does not exist or is not supported\nFailed to execute (AddSubtype).\n"}
{"asctime": "2020-03-26 13:08:56,898", "levelname": "DEBUG", "message": "CreateFeatureClass :Setting subtype code C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure,Type,20,Chamber failed"}
{"asctime": "2020-03-26 13:08:56,899", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure does not exist or is not supported\nFailed to execute (AddSubtype).\n"}
{"asctime": "2020-03-26 13:08:56,900", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 142, in _process_subtypes\n    arcpy.AddSubtype_management(full_fc, code, st_vals[code])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19589, in AddSubtype\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19586, in AddSubtype\n    retval = convertArcObjectToPythonObject(gp.AddSubtype_management(*gp_fixargs((in_table, subtype_code, subtype_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure does not exist or is not supported\nFailed to execute (AddSubtype).\n"}
{"asctime": "2020-03-26 13:08:56,990", "levelname": "DEBUG", "message": "CreateFeatureClass :Setting subtype code C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure,Type,21,Pole failed"}
{"asctime": "2020-03-26 13:08:56,991", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure does not exist or is not supported\nFailed to execute (AddSubtype).\n"}
{"asctime": "2020-03-26 13:08:56,992", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 142, in _process_subtypes\n    arcpy.AddSubtype_management(full_fc, code, st_vals[code])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19589, in AddSubtype\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19586, in AddSubtype\n    retval = convertArcObjectToPythonObject(gp.AddSubtype_management(*gp_fixargs((in_table, subtype_code, subtype_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000732: Input Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure does not exist or is not supported\nFailed to execute (AddSubtype).\n"}
{"asctime": "2020-03-26 13:08:57,167", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't add relationship for to Route_Cable"}
{"asctime": "2020-03-26 13:08:57,168", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000732: Origin Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Route does not exist or is not supported\nERROR 000732: Destination Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Cable does not exist or is not supported\nFailed to execute (CreateRelationshipClass).\n"}
{"asctime": "2020-03-26 13:08:57,168", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 88, in _process_relationship_classes\n    arcpy.CreateRelationshipClass_management(f\"{self._connection}/{a_relationship['origin']}\",f\"{self._connection}/{a_relationship['destination']}\", a_relationship['outclass'], a_relationship['type'], a_relationship['forwardlabel'], a_relationship['backlabel'], a_relationship['message'], a_relationship['cardinality'], a_relationship['attributed'], a_relationship['originpk'], a_relationship['originfk'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19096, in CreateRelationshipClass\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19093, in CreateRelationshipClass\n    retval = convertArcObjectToPythonObject(gp.CreateRelationshipClass_management(*gp_fixargs((origin_table, destination_table, out_relationship_class, relationship_type, forward_label, backward_label, message_direction, cardinality, attributed, origin_primary_key, origin_foreign_key, destination_primary_key, destination_foreign_key), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000732: Origin Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Route does not exist or is not supported\nERROR 000732: Destination Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Cable does not exist or is not supported\nFailed to execute (CreateRelationshipClass).\n"}
{"asctime": "2020-03-26 13:08:57,350", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't add relationship for to Route_SupportingStructure"}
{"asctime": "2020-03-26 13:08:57,351", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000732: Origin Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Route does not exist or is not supported\nERROR 000732: Destination Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/SupportingStructure does not exist or is not supported\nFailed to execute (CreateRelationshipClass).\n"}
{"asctime": "2020-03-26 13:08:57,351", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 88, in _process_relationship_classes\n    arcpy.CreateRelationshipClass_management(f\"{self._connection}/{a_relationship['origin']}\",f\"{self._connection}/{a_relationship['destination']}\", a_relationship['outclass'], a_relationship['type'], a_relationship['forwardlabel'], a_relationship['backlabel'], a_relationship['message'], a_relationship['cardinality'], a_relationship['attributed'], a_relationship['originpk'], a_relationship['originfk'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19096, in CreateRelationshipClass\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19093, in CreateRelationshipClass\n    retval = convertArcObjectToPythonObject(gp.CreateRelationshipClass_management(*gp_fixargs((origin_table, destination_table, out_relationship_class, relationship_type, forward_label, backward_label, message_direction, cardinality, attributed, origin_primary_key, origin_foreign_key, destination_primary_key, destination_foreign_key), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000732: Origin Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Route does not exist or is not supported\nERROR 000732: Destination Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/SupportingStructure does not exist or is not supported\nFailed to execute (CreateRelationshipClass).\n"}
{"asctime": "2020-03-26 13:08:57,511", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't add relationship for to Cable_AssociatedStructure"}
{"asctime": "2020-03-26 13:08:57,512", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000732: Origin Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Cable does not exist or is not supported\nERROR 000732: Destination Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/AssociatedStructure does not exist or is not supported\nFailed to execute (CreateRelationshipClass).\n"}
{"asctime": "2020-03-26 13:08:57,512", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 88, in _process_relationship_classes\n    arcpy.CreateRelationshipClass_management(f\"{self._connection}/{a_relationship['origin']}\",f\"{self._connection}/{a_relationship['destination']}\", a_relationship['outclass'], a_relationship['type'], a_relationship['forwardlabel'], a_relationship['backlabel'], a_relationship['message'], a_relationship['cardinality'], a_relationship['attributed'], a_relationship['originpk'], a_relationship['originfk'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19096, in CreateRelationshipClass\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19093, in CreateRelationshipClass\n    retval = convertArcObjectToPythonObject(gp.CreateRelationshipClass_management(*gp_fixargs((origin_table, destination_table, out_relationship_class, relationship_type, forward_label, backward_label, message_direction, cardinality, attributed, origin_primary_key, origin_foreign_key, destination_primary_key, destination_foreign_key), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000732: Origin Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Cable does not exist or is not supported\nERROR 000732: Destination Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/AssociatedStructure does not exist or is not supported\nFailed to execute (CreateRelationshipClass).\n"}
{"asctime": "2020-03-26 13:08:57,667", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't add relationship for to CentralOffice_CentralOfficeArea"}
{"asctime": "2020-03-26 13:08:57,668", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000732: Origin Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CentralOffice does not exist or is not supported\nERROR 000732: Destination Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CentralOfficeArea does not exist or is not supported\nFailed to execute (CreateRelationshipClass).\n"}
{"asctime": "2020-03-26 13:08:57,669", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 88, in _process_relationship_classes\n    arcpy.CreateRelationshipClass_management(f\"{self._connection}/{a_relationship['origin']}\",f\"{self._connection}/{a_relationship['destination']}\", a_relationship['outclass'], a_relationship['type'], a_relationship['forwardlabel'], a_relationship['backlabel'], a_relationship['message'], a_relationship['cardinality'], a_relationship['attributed'], a_relationship['originpk'], a_relationship['originfk'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19096, in CreateRelationshipClass\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19093, in CreateRelationshipClass\n    retval = convertArcObjectToPythonObject(gp.CreateRelationshipClass_management(*gp_fixargs((origin_table, destination_table, out_relationship_class, relationship_type, forward_label, backward_label, message_direction, cardinality, attributed, origin_primary_key, origin_foreign_key, destination_primary_key, destination_foreign_key), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000732: Origin Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CentralOffice does not exist or is not supported\nERROR 000732: Destination Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CentralOfficeArea does not exist or is not supported\nFailed to execute (CreateRelationshipClass).\n"}
{"asctime": "2020-03-26 13:08:57,827", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't add relationship for to CentralOffice_CentralOfficeDetail"}
{"asctime": "2020-03-26 13:08:57,828", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000732: Origin Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CentralOffice does not exist or is not supported\nERROR 000732: Destination Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CentralOfficeDetail does not exist or is not supported\nFailed to execute (CreateRelationshipClass).\n"}
{"asctime": "2020-03-26 13:08:57,829", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 88, in _process_relationship_classes\n    arcpy.CreateRelationshipClass_management(f\"{self._connection}/{a_relationship['origin']}\",f\"{self._connection}/{a_relationship['destination']}\", a_relationship['outclass'], a_relationship['type'], a_relationship['forwardlabel'], a_relationship['backlabel'], a_relationship['message'], a_relationship['cardinality'], a_relationship['attributed'], a_relationship['originpk'], a_relationship['originfk'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19096, in CreateRelationshipClass\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19093, in CreateRelationshipClass\n    retval = convertArcObjectToPythonObject(gp.CreateRelationshipClass_management(*gp_fixargs((origin_table, destination_table, out_relationship_class, relationship_type, forward_label, backward_label, message_direction, cardinality, attributed, origin_primary_key, origin_foreign_key, destination_primary_key, destination_foreign_key), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000732: Origin Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CentralOffice does not exist or is not supported\nERROR 000732: Destination Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CentralOfficeDetail does not exist or is not supported\nFailed to execute (CreateRelationshipClass).\n"}
{"asctime": "2020-03-26 13:08:57,987", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't add relationship for to CentralOffice_CentralOfficeDetail"}
{"asctime": "2020-03-26 13:08:57,988", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000732: Origin Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure does not exist or is not supported\nERROR 000732: Destination Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CentralOfficeDetail does not exist or is not supported\nFailed to execute (CreateRelationshipClass).\n"}
{"asctime": "2020-03-26 13:08:57,989", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 88, in _process_relationship_classes\n    arcpy.CreateRelationshipClass_management(f\"{self._connection}/{a_relationship['origin']}\",f\"{self._connection}/{a_relationship['destination']}\", a_relationship['outclass'], a_relationship['type'], a_relationship['forwardlabel'], a_relationship['backlabel'], a_relationship['message'], a_relationship['cardinality'], a_relationship['attributed'], a_relationship['originpk'], a_relationship['originfk'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19096, in CreateRelationshipClass\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 19093, in CreateRelationshipClass\n    retval = convertArcObjectToPythonObject(gp.CreateRelationshipClass_management(*gp_fixargs((origin_table, destination_table, out_relationship_class, relationship_type, forward_label, backward_label, message_direction, cardinality, attributed, origin_primary_key, origin_foreign_key, destination_primary_key, destination_foreign_key), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000732: Origin Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Structure does not exist or is not supported\nERROR 000732: Destination Table: Dataset C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CentralOfficeDetail does not exist or is not supported\nFailed to execute (CreateRelationshipClass).\n"}
{"asctime": "2020-03-26 13:08:58,184", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't create domain ApprovalStatus"}
{"asctime": "2020-03-26 13:08:58,184", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 13:08:58,185", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 13:09:04,548", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineChangeArea', 'geometry': 'POLYGON', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinechangearea.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 13:09:04,811", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlineChangeArea exists."}
{"asctime": "2020-03-26 13:09:04,811", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 13:09:06,491", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class RedlineChangeArea"}
{"asctime": "2020-03-26 13:09:08,858", "levelname": "DEBUG", "message": "CreateFeatureClass :RedlineChangeArea created"}
{"asctime": "2020-03-26 13:09:08,859", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 13:09:08,860", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Description"}
{"asctime": "2020-03-26 13:09:10,808", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Description added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 13:09:10,809", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comments"}
{"asctime": "2020-03-26 13:09:12,954", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Comments added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 13:09:12,955", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying ApprovalStatus"}
{"asctime": "2020-03-26 13:09:15,336", "levelname": "DEBUG", "message": "CreateFeatureClass :Field ApprovalStatus added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 13:09:15,336", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying ChangeId"}
{"asctime": "2020-03-26 13:09:17,151", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field ChangeId failed"}
{"asctime": "2020-03-26 13:09:17,151", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000356: Invalid domain type.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:09:17,152", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000356: Invalid domain type.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:09:17,155", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 13:09:17,648", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 13:09:17,649", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:09:17,650", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:09:17,652", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 13:09:19,735", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 13:09:19,736", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlinePointMarker', 'geometry': 'POINT', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinepointmarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': True}"}
{"asctime": "2020-03-26 13:09:19,960", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlinePointMarker exists."}
{"asctime": "2020-03-26 13:09:19,960", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 13:09:21,556", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class RedlinePointMarker"}
{"asctime": "2020-03-26 13:09:23,844", "levelname": "DEBUG", "message": "CreateFeatureClass :RedlinePointMarker created"}
{"asctime": "2020-03-26 13:09:23,845", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 13:09:23,845", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Label"}
{"asctime": "2020-03-26 13:09:25,801", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Label added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 13:09:25,802", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comments"}
{"asctime": "2020-03-26 13:09:28,044", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Comments added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 13:09:28,045", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 13:09:28,528", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 13:09:28,529", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:09:28,530", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:09:28,532", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 13:09:30,461", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 13:09:30,462", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineLineMarker', 'geometry': 'POLYLINE', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinelinemarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 13:09:30,686", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlineLineMarker exists."}
{"asctime": "2020-03-26 13:09:30,687", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 13:09:32,753", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class RedlineLineMarker"}
{"asctime": "2020-03-26 13:09:35,327", "levelname": "DEBUG", "message": "CreateFeatureClass :RedlineLineMarker created"}
{"asctime": "2020-03-26 13:09:35,328", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 13:09:35,329", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Label"}
{"asctime": "2020-03-26 13:09:37,305", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Label added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 13:09:37,306", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comments"}
{"asctime": "2020-03-26 13:09:40,059", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Comments added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 13:09:40,060", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 13:09:40,566", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 13:09:40,567", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:09:40,568", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:09:40,570", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 13:09:42,541", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 13:09:42,542", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineComment', 'geometry': '', 'spatialref': '', 'fields': 'redlinecomment.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 13:09:42,773", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlineComment exists."}
{"asctime": "2020-03-26 13:09:42,774", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 13:09:44,219", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating table RedlineComment"}
{"asctime": "2020-03-26 13:09:46,881", "levelname": "DEBUG", "message": "CreateFeatureClass :RedlineComment created"}
{"asctime": "2020-03-26 13:09:46,882", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 13:09:46,884", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying ApprovalStatus"}
{"asctime": "2020-03-26 13:09:49,241", "levelname": "DEBUG", "message": "CreateFeatureClass :Field ApprovalStatus added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 13:09:49,242", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comment"}
{"asctime": "2020-03-26 13:09:51,001", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Comment added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 13:09:51,002", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 13:09:51,509", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 13:09:51,509", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:09:51,510", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:09:51,513", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 13:09:53,346", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 13:09:53,347", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineCommentId"}
{"asctime": "2020-03-26 13:09:55,167", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineCommentId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 13:09:55,167", "levelname": "DEBUG", "message": "CreateFeatureClass :Processing feature classes finished."}
{"asctime": "2020-03-26 13:09:55,169", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'FieldingAreaMarker', 'geometry': 'POLYGON', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'fieldingareamarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': True}"}
{"asctime": "2020-03-26 13:09:55,460", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class FieldingAreaMarker"}
{"asctime": "2020-03-26 13:09:57,913", "levelname": "DEBUG", "message": "CreateFeatureClass :FieldingAreaMarker created"}
{"asctime": "2020-03-26 13:09:57,915", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtmarkupdatamodel.gdb/FieldingAreaMarker"}
{"asctime": "2020-03-26 13:09:57,916", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Label"}
{"asctime": "2020-03-26 13:09:59,890", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Label added to C:/Cloud/Dropbox/Work/Axin/rdtmarkupdatamodel.gdb/FieldingAreaMarker"}
{"asctime": "2020-03-26 13:09:59,890", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comments"}
{"asctime": "2020-03-26 13:10:01,884", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Comments added to C:/Cloud/Dropbox/Work/Axin/rdtmarkupdatamodel.gdb/FieldingAreaMarker"}
{"asctime": "2020-03-26 13:10:01,885", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 13:10:02,393", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 13:10:02,394", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:10:02,395", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:10:02,397", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'FieldingPointMarker', 'geometry': 'POINT', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'fieldingpointmarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': True}"}
{"asctime": "2020-03-26 13:10:02,680", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class FieldingPointMarker"}
{"asctime": "2020-03-26 13:10:05,016", "levelname": "DEBUG", "message": "CreateFeatureClass :FieldingPointMarker created"}
{"asctime": "2020-03-26 13:10:05,017", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtmarkupdatamodel.gdb/FieldingPointMarker"}
{"asctime": "2020-03-26 13:10:05,018", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Label"}
{"asctime": "2020-03-26 13:10:07,022", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Label added to C:/Cloud/Dropbox/Work/Axin/rdtmarkupdatamodel.gdb/FieldingPointMarker"}
{"asctime": "2020-03-26 13:10:07,023", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comments"}
{"asctime": "2020-03-26 13:10:09,077", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Comments added to C:/Cloud/Dropbox/Work/Axin/rdtmarkupdatamodel.gdb/FieldingPointMarker"}
{"asctime": "2020-03-26 13:10:09,078", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 13:10:09,572", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 13:10:09,573", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:10:09,574", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:10:09,576", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'FieldingLineMarker', 'geometry': 'POLYLINE', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'fieldinglinemarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': True}"}
{"asctime": "2020-03-26 13:10:09,869", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class FieldingLineMarker"}
{"asctime": "2020-03-26 13:10:12,890", "levelname": "DEBUG", "message": "CreateFeatureClass :FieldingLineMarker created"}
{"asctime": "2020-03-26 13:10:12,891", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtmarkupdatamodel.gdb/FieldingLineMarker"}
{"asctime": "2020-03-26 13:10:12,892", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Label"}
{"asctime": "2020-03-26 13:10:14,840", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Label added to C:/Cloud/Dropbox/Work/Axin/rdtmarkupdatamodel.gdb/FieldingLineMarker"}
{"asctime": "2020-03-26 13:10:14,841", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comments"}
{"asctime": "2020-03-26 13:10:16,751", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Comments added to C:/Cloud/Dropbox/Work/Axin/rdtmarkupdatamodel.gdb/FieldingLineMarker"}
{"asctime": "2020-03-26 13:10:16,751", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 13:10:17,272", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 13:10:17,272", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:10:17,273", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:10:17,276", "levelname": "DEBUG", "message": "CreateFeatureClass :Processing feature classes finished."}
{"asctime": "2020-03-26 13:17:15,379", "levelname": "DEBUG", "message": "CreateFeatureClass :Class:CreateFeatureClass"}
{"asctime": "2020-03-26 13:17:15,382", "levelname": "DEBUG", "message": "CreateFeatureClass :loaded config for CreateFeatureClass from c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.json"}
{"asctime": "2020-03-26 13:17:15,382", "levelname": "DEBUG", "message": "CreateFeatureClass :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas"}
{"asctime": "2020-03-26 13:17:15,382", "levelname": "DEBUG", "message": "CreateFeatureClass :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas/prjs/prjs.gdb"}
{"asctime": "2020-03-26 13:17:41,696", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't add coded value 0 to SplitterAreaType"}
{"asctime": "2020-03-26 13:17:41,697", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-03-26 13:17:41,697", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 110, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-03-26 13:17:42,300", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't add coded value 1 to SplitterAreaType"}
{"asctime": "2020-03-26 13:17:42,301", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-03-26 13:17:42,301", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 110, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-03-26 13:17:58,823", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't create domain WorkAreaCableType"}
{"asctime": "2020-03-26 13:17:58,824", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 002834: The geometry operation was cancelled.\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 13:17:58,824", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 002834: The geometry operation was cancelled.\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 13:17:59,021", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't add coded value 0 to WorkAreaCableType"}
{"asctime": "2020-03-26 13:17:59,021", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000800: The value is not a member of AssociatedStructType | CabinetType | CableMaterial | CableSize | ChamberType | Colour | ConduitInstallationType | ConduitSize | DipType | FiberTerminalTail | FiberTerminalType | HandholeType | PedestalType | PoleType | SpliceEnclosureType | SplitterAreaType | SplitterType | StoredSlackLength | StrandInstallationType | StrandSize | TerminalAreaType | TrueFalse | WorkAreaArchitecture.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-03-26 13:17:59,022", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 110, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000800: The value is not a member of AssociatedStructType | CabinetType | CableMaterial | CableSize | ChamberType | Colour | ConduitInstallationType | ConduitSize | DipType | FiberTerminalTail | FiberTerminalType | HandholeType | PedestalType | PoleType | SpliceEnclosureType | SplitterAreaType | SplitterType | StoredSlackLength | StrandInstallationType | StrandSize | TerminalAreaType | TrueFalse | WorkAreaArchitecture.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-03-26 13:17:59,235", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't add coded value 1 to WorkAreaCableType"}
{"asctime": "2020-03-26 13:17:59,235", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000800: The value is not a member of AssociatedStructType | CabinetType | CableMaterial | CableSize | ChamberType | Colour | ConduitInstallationType | ConduitSize | DipType | FiberTerminalTail | FiberTerminalType | HandholeType | PedestalType | PoleType | SpliceEnclosureType | SplitterAreaType | SplitterType | StoredSlackLength | StrandInstallationType | StrandSize | TerminalAreaType | TrueFalse | WorkAreaArchitecture.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-03-26 13:17:59,236", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 110, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000800: The value is not a member of AssociatedStructType | CabinetType | CableMaterial | CableSize | ChamberType | Colour | ConduitInstallationType | ConduitSize | DipType | FiberTerminalTail | FiberTerminalType | HandholeType | PedestalType | PoleType | SpliceEnclosureType | SplitterAreaType | SplitterType | StoredSlackLength | StrandInstallationType | StrandSize | TerminalAreaType | TrueFalse | WorkAreaArchitecture.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-03-26 13:18:03,311", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'Assembly', 'geometry': '', 'spatialref': '', 'fields': 'assembly.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 13:18:03,359", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating table Assembly"}
{"asctime": "2020-03-26 13:18:05,956", "levelname": "DEBUG", "message": "CreateFeatureClass :Assembly created"}
{"asctime": "2020-03-26 13:18:05,958", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Assembly"}
{"asctime": "2020-03-26 13:18:05,959", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 13:18:06,471", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 13:18:06,472", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:18:06,472", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:18:06,474", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying AssemblyId"}
{"asctime": "2020-03-26 13:18:08,037", "levelname": "DEBUG", "message": "CreateFeatureClass :Field AssemblyId added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Assembly"}
{"asctime": "2020-03-26 13:18:08,038", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying StructureId"}
{"asctime": "2020-03-26 13:18:09,634", "levelname": "DEBUG", "message": "CreateFeatureClass :Field StructureId added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Assembly"}
{"asctime": "2020-03-26 13:18:09,634", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RUSCode"}
{"asctime": "2020-03-26 13:18:11,244", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RUSCode added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Assembly"}
{"asctime": "2020-03-26 13:18:11,245", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'AssociatedStructure', 'geometry': '', 'spatialref': '', 'fields': 'associatedstructure.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 13:18:11,299", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating table AssociatedStructure"}
{"asctime": "2020-03-26 13:18:13,427", "levelname": "DEBUG", "message": "CreateFeatureClass :AssociatedStructure created"}
{"asctime": "2020-03-26 13:18:13,428", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/AssociatedStructure"}
{"asctime": "2020-03-26 13:18:13,429", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 13:18:13,876", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 13:18:13,877", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:18:13,878", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:18:13,880", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying StructureId"}
{"asctime": "2020-03-26 13:18:15,610", "levelname": "DEBUG", "message": "CreateFeatureClass :Field StructureId added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/AssociatedStructure"}
{"asctime": "2020-03-26 13:18:15,610", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying CableId"}
{"asctime": "2020-03-26 13:18:17,307", "levelname": "DEBUG", "message": "CreateFeatureClass :Field CableId added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/AssociatedStructure"}
{"asctime": "2020-03-26 13:18:17,308", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying StructureType"}
{"asctime": "2020-03-26 13:18:18,959", "levelname": "DEBUG", "message": "CreateFeatureClass :Field StructureType added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/AssociatedStructure"}
{"asctime": "2020-03-26 13:18:18,959", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying StartStructure"}
{"asctime": "2020-03-26 13:18:20,707", "levelname": "DEBUG", "message": "CreateFeatureClass :Field StartStructure added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/AssociatedStructure"}
{"asctime": "2020-03-26 13:18:20,708", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying EndStructure"}
{"asctime": "2020-03-26 13:18:22,412", "levelname": "DEBUG", "message": "CreateFeatureClass :Field EndStructure added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/AssociatedStructure"}
{"asctime": "2020-03-26 13:18:22,413", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'Cable', 'geometry': 'POLYLINE', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'cable.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 13:18:22,683", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class Cable"}
{"asctime": "2020-03-26 13:18:24,840", "levelname": "DEBUG", "message": "CreateFeatureClass :Cable created"}
{"asctime": "2020-03-26 13:18:24,842", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Cable"}
{"asctime": "2020-03-26 13:18:24,843", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 13:18:25,287", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 13:18:25,288", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:18:25,288", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:18:25,291", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying CableId"}
{"asctime": "2020-03-26 13:18:27,140", "levelname": "DEBUG", "message": "CreateFeatureClass :Field CableId added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Cable"}
{"asctime": "2020-03-26 13:18:27,140", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RouteId"}
{"asctime": "2020-03-26 13:18:28,864", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RouteId added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Cable"}
{"asctime": "2020-03-26 13:18:28,865", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying SupportingStructureId"}
{"asctime": "2020-03-26 13:18:30,546", "levelname": "DEBUG", "message": "CreateFeatureClass :Field SupportingStructureId added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Cable"}
{"asctime": "2020-03-26 13:18:30,547", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Size"}
{"asctime": "2020-03-26 13:18:32,026", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Size added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Cable"}
{"asctime": "2020-03-26 13:18:32,026", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Material"}
{"asctime": "2020-03-26 13:18:33,455", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Material added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Cable"}
{"asctime": "2020-03-26 13:18:33,456", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying SheathId"}
{"asctime": "2020-03-26 13:18:34,874", "levelname": "DEBUG", "message": "CreateFeatureClass :Field SheathId added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Cable"}
{"asctime": "2020-03-26 13:18:34,875", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying SectionId"}
{"asctime": "2020-03-26 13:18:36,288", "levelname": "DEBUG", "message": "CreateFeatureClass :Field SectionId added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Cable"}
{"asctime": "2020-03-26 13:18:36,289", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying WorkId"}
{"asctime": "2020-03-26 13:18:37,697", "levelname": "DEBUG", "message": "CreateFeatureClass :Field WorkId added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Cable"}
{"asctime": "2020-03-26 13:18:37,697", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Type"}
{"asctime": "2020-03-26 13:18:39,305", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Type added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Cable"}
{"asctime": "2020-03-26 13:18:39,306", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying CustomerServicePointId"}
{"asctime": "2020-03-26 13:18:41,778", "levelname": "DEBUG", "message": "CreateFeatureClass :Field CustomerServicePointId added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Cable"}
{"asctime": "2020-03-26 13:18:41,779", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying CentralOfficeDetailId"}
{"asctime": "2020-03-26 13:18:43,779", "levelname": "DEBUG", "message": "CreateFeatureClass :Field CentralOfficeDetailId added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Cable"}
{"asctime": "2020-03-26 13:18:43,780", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RangeLabel"}
{"asctime": "2020-03-26 13:18:45,808", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RangeLabel added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/Cable"}
{"asctime": "2020-03-26 13:18:45,809", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'CableFeature', 'geometry': 'POINT', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'cablefeature.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 13:18:46,095", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class CableFeature"}
{"asctime": "2020-03-26 13:18:48,296", "levelname": "DEBUG", "message": "CreateFeatureClass :CableFeature created"}
{"asctime": "2020-03-26 13:18:48,297", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CableFeature"}
{"asctime": "2020-03-26 13:18:48,299", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 13:18:48,765", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 13:18:48,766", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:18:48,767", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:18:48,769", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Type"}
{"asctime": "2020-03-26 13:18:50,667", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Type added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CableFeature"}
{"asctime": "2020-03-26 13:18:50,668", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying WorkId"}
{"asctime": "2020-03-26 13:18:52,293", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field WorkId failed"}
{"asctime": "2020-03-26 13:18:52,293", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:18:52,294", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:18:52,295", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comment"}
{"asctime": "2020-03-26 13:18:54,138", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Comment added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CableFeature"}
{"asctime": "2020-03-26 13:18:54,138", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying FeatureType"}
{"asctime": "2020-03-26 13:18:56,021", "levelname": "DEBUG", "message": "CreateFeatureClass :Field FeatureType added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CableFeature"}
{"asctime": "2020-03-26 13:18:56,021", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying FromCableId"}
{"asctime": "2020-03-26 13:18:57,855", "levelname": "DEBUG", "message": "CreateFeatureClass :Field FromCableId added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CableFeature"}
{"asctime": "2020-03-26 13:18:57,856", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying ToCableId"}
{"asctime": "2020-03-26 13:18:59,803", "levelname": "DEBUG", "message": "CreateFeatureClass :Field ToCableId added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CableFeature"}
{"asctime": "2020-03-26 13:18:59,804", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'CentralOffice', 'geometry': 'POINT', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'centraloffice.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 13:19:00,078", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class CentralOffice"}
{"asctime": "2020-03-26 13:19:02,255", "levelname": "DEBUG", "message": "CreateFeatureClass :CentralOffice created"}
{"asctime": "2020-03-26 13:19:02,256", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CentralOffice"}
{"asctime": "2020-03-26 13:19:02,257", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 13:19:02,756", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 13:19:02,757", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:19:02,758", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:19:02,760", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying CentralOfficeId"}
{"asctime": "2020-03-26 13:19:04,939", "levelname": "DEBUG", "message": "CreateFeatureClass :Field CentralOfficeId added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CentralOffice"}
{"asctime": "2020-03-26 13:19:04,940", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Type"}
{"asctime": "2020-03-26 13:19:06,866", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Type added to C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CentralOffice"}
{"asctime": "2020-03-26 13:19:06,867", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'CentralOfficeDetail', 'geometry': '', 'spatialref': '', 'fields': 'centralofficedetail.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 13:19:06,910", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating table CentralOfficeDetail"}
{"asctime": "2020-03-26 13:19:09,235", "levelname": "DEBUG", "message": "CreateFeatureClass :CentralOfficeDetail created"}
{"asctime": "2020-03-26 13:19:09,237", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtdesigndatamodel.gdb/CentralOfficeDetail"}
{"asctime": "2020-03-26 13:19:09,238", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 13:19:09,704", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 13:19:09,705", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 13:19:09,706", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
