{"asctime": "2020-03-26 14:19:27,794", "levelname": "DEBUG", "message": "CreateFeatureClass :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas/prjs/prjs.gdb"}
{"asctime": "2020-03-26 14:19:31,116", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't create domain ApprovalStatus"}
{"asctime": "2020-03-26 14:19:31,117", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 14:19:31,117", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 14:19:45,538", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineChangeArea', 'geometry': 'POLYGON', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinechangearea.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 14:19:51,550", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlineChangeArea exists."}
{"asctime": "2020-03-26 14:19:52,726", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 14:20:24,862", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:20:24,864", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 191, in _create_feature_class\n    arcpy.Delete_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5352, in Delete\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5349, in Delete\n    retval = convertArcObjectToPythonObject(gp.Delete_management(*gp_fixargs((in_data, data_type), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:20:26,187", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlinePointMarker', 'geometry': 'POINT', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinepointmarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': True}"}
{"asctime": "2020-03-26 14:20:26,407", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlinePointMarker exists."}
{"asctime": "2020-03-26 14:20:26,408", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 14:20:59,101", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:20:59,102", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 191, in _create_feature_class\n    arcpy.Delete_management(full_fc)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5352, in Delete\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 5349, in Delete\n    retval = convertArcObjectToPythonObject(gp.Delete_management(*gp_fixargs((in_data, data_type), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000317: C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker cannot be deleted\nFailed to execute (Delete).\n"}
{"asctime": "2020-03-26 14:21:00,262", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineLineMarker', 'geometry': 'POLYLINE', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinelinemarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 14:21:00,452", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlineLineMarker exists."}
{"asctime": "2020-03-26 14:21:00,453", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 14:21:19,378", "levelname": "DEBUG", "message": "CreateFeatureClass :Class:CreateFeatureClass"}
{"asctime": "2020-03-26 14:21:19,381", "levelname": "DEBUG", "message": "CreateFeatureClass :loaded config for CreateFeatureClass from c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.json"}
{"asctime": "2020-03-26 14:21:19,382", "levelname": "DEBUG", "message": "CreateFeatureClass :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas"}
{"asctime": "2020-03-26 14:21:19,382", "levelname": "DEBUG", "message": "CreateFeatureClass :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas/prjs/prjs.gdb"}
{"asctime": "2020-03-26 14:21:23,296", "levelname": "DEBUG", "message": "CreateFeatureClass :Can't create domain ApprovalStatus"}
{"asctime": "2020-03-26 14:21:23,297", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 14:21:23,298", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 14:21:30,702", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineChangeArea', 'geometry': 'POLYGON', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinechangearea.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 14:21:30,903", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlineChangeArea exists."}
{"asctime": "2020-03-26 14:21:30,904", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 14:21:36,821", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class RedlineChangeArea"}
{"asctime": "2020-03-26 14:21:38,886", "levelname": "DEBUG", "message": "CreateFeatureClass :RedlineChangeArea created"}
{"asctime": "2020-03-26 14:21:38,887", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 14:21:38,887", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Description"}
{"asctime": "2020-03-26 14:21:40,553", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Description added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 14:21:40,553", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comments"}
{"asctime": "2020-03-26 14:21:42,269", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Comments added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 14:21:42,269", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying ApprovalStatus"}
{"asctime": "2020-03-26 14:21:44,042", "levelname": "DEBUG", "message": "CreateFeatureClass :Field ApprovalStatus added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 14:21:44,042", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying ChangeId"}
{"asctime": "2020-03-26 14:21:45,576", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field ChangeId failed"}
{"asctime": "2020-03-26 14:21:45,577", "levelname": "ERROR", "message": "CreateFeatureClass :ERROR 000356: Invalid domain type.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:21:45,577", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000356: Invalid domain type.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:21:45,579", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 14:21:46,020", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 14:21:46,021", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:21:46,021", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:21:46,023", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 14:21:47,703", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 14:21:48,705", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlinePointMarker', 'geometry': 'POINT', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinepointmarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': True}"}
{"asctime": "2020-03-26 14:21:48,897", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlinePointMarker exists."}
{"asctime": "2020-03-26 14:21:48,897", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 14:21:50,857", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class RedlinePointMarker"}
{"asctime": "2020-03-26 14:21:52,753", "levelname": "DEBUG", "message": "CreateFeatureClass :RedlinePointMarker created"}
{"asctime": "2020-03-26 14:21:52,754", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 14:21:52,755", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Label"}
{"asctime": "2020-03-26 14:21:54,425", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Label added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 14:21:54,426", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comments"}
{"asctime": "2020-03-26 14:21:56,010", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Comments added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 14:21:56,010", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 14:21:56,413", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 14:21:56,414", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:21:56,414", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:21:56,416", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 14:21:58,019", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 14:21:59,252", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineLineMarker', 'geometry': 'POLYLINE', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinelinemarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 14:21:59,528", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating feature class RedlineLineMarker"}
{"asctime": "2020-03-26 14:22:01,611", "levelname": "DEBUG", "message": "CreateFeatureClass :RedlineLineMarker created"}
{"asctime": "2020-03-26 14:22:01,612", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 14:22:01,612", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Label"}
{"asctime": "2020-03-26 14:22:03,295", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Label added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 14:22:03,296", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comments"}
{"asctime": "2020-03-26 14:22:04,944", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Comments added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 14:22:04,945", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 14:22:05,353", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 14:22:05,354", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:22:05,354", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:22:05,356", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 14:22:06,910", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 14:22:08,292", "levelname": "DEBUG", "message": "CreateFeatureClass :{'name': 'RedlineComment', 'geometry': '', 'spatialref': '', 'fields': 'redlinecomment.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 14:22:08,485", "levelname": "DEBUG", "message": "CreateFeatureClass :Feature class RedlineComment exists."}
{"asctime": "2020-03-26 14:22:08,485", "levelname": "DEBUG", "message": "CreateFeatureClass :We have clearance to delete Clarence."}
{"asctime": "2020-03-26 14:22:09,354", "levelname": "DEBUG", "message": "CreateFeatureClass :Creating table RedlineComment"}
{"asctime": "2020-03-26 14:22:11,179", "levelname": "DEBUG", "message": "CreateFeatureClass :RedlineComment created"}
{"asctime": "2020-03-26 14:22:11,180", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 14:22:11,180", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying ApprovalStatus"}
{"asctime": "2020-03-26 14:22:12,565", "levelname": "DEBUG", "message": "CreateFeatureClass :Field ApprovalStatus added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 14:22:12,566", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying Comment"}
{"asctime": "2020-03-26 14:22:13,962", "levelname": "DEBUG", "message": "CreateFeatureClass :Field Comment added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 14:22:13,963", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying OBJECTID"}
{"asctime": "2020-03-26 14:22:14,344", "levelname": "DEBUG", "message": "CreateFeatureClass :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 14:22:14,344", "levelname": "ERROR", "message": "CreateFeatureClass :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:22:14,345", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\CreateFeatureClass.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 14:22:14,347", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 14:22:15,780", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 14:22:15,781", "levelname": "DEBUG", "message": "CreateFeatureClass :Applying RedlineCommentId"}
{"asctime": "2020-03-26 14:22:17,291", "levelname": "DEBUG", "message": "CreateFeatureClass :Field RedlineCommentId added to C:/Cloud/Dropbox/Work/Axin/rdtrldatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 14:22:18,166", "levelname": "DEBUG", "message": "CreateFeatureClass :Processing feature classes finished."}
{"asctime": "2020-03-26 17:11:45,049", "levelname": "DEBUG", "message": "ApplyDataModel :Class:ApplyDataModel"}
{"asctime": "2020-03-26 17:11:45,052", "levelname": "DEBUG", "message": "ApplyDataModel :loaded config for ApplyDataModel from c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.json"}
{"asctime": "2020-03-26 17:11:45,053", "levelname": "DEBUG", "message": "ApplyDataModel :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas"}
{"asctime": "2020-03-26 17:11:45,053", "levelname": "DEBUG", "message": "ApplyDataModel :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas/prjs/prjs.gdb"}
{"asctime": "2020-03-26 17:11:56,158", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'RedlineChangeArea', 'geometry': 'POLYGON', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinechangearea.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 17:11:56,397", "levelname": "DEBUG", "message": "ApplyDataModel :Creating feature class RedlineChangeArea"}
{"asctime": "2020-03-26 17:11:58,320", "levelname": "DEBUG", "message": "ApplyDataModel :RedlineChangeArea created"}
{"asctime": "2020-03-26 17:11:58,321", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtredlinedatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 17:11:58,321", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Description"}
{"asctime": "2020-03-26 17:11:59,948", "levelname": "DEBUG", "message": "ApplyDataModel :Field Description added to C:/Cloud/Dropbox/Work/Axin/rdtredlinedatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 17:11:59,949", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Comments"}
{"asctime": "2020-03-26 17:12:01,579", "levelname": "DEBUG", "message": "ApplyDataModel :Field Comments added to C:/Cloud/Dropbox/Work/Axin/rdtredlinedatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 17:12:01,580", "levelname": "DEBUG", "message": "ApplyDataModel :Applying ApprovalStatus"}
{"asctime": "2020-03-26 17:12:03,357", "levelname": "DEBUG", "message": "ApplyDataModel :Field ApprovalStatus added to C:/Cloud/Dropbox/Work/Axin/rdtredlinedatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 17:12:03,358", "levelname": "DEBUG", "message": "ApplyDataModel :Applying ChangeId"}
{"asctime": "2020-03-26 17:12:04,924", "levelname": "DEBUG", "message": "ApplyDataModel :Adding field ChangeId failed"}
{"asctime": "2020-03-26 17:12:04,925", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000356: Invalid domain type.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 17:12:04,925", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000356: Invalid domain type.\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 17:12:04,936", "levelname": "DEBUG", "message": "ApplyDataModel :Applying OBJECTID"}
{"asctime": "2020-03-26 17:12:05,368", "levelname": "DEBUG", "message": "ApplyDataModel :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 17:12:05,368", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 17:12:05,369", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 17:12:05,371", "levelname": "DEBUG", "message": "ApplyDataModel :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 17:12:07,266", "levelname": "DEBUG", "message": "ApplyDataModel :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtredlinedatamodel.gdb/RedlineChangeArea"}
{"asctime": "2020-03-26 17:12:07,266", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'RedlinePointMarker', 'geometry': 'POINT', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinepointmarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': True}"}
{"asctime": "2020-03-26 17:12:07,509", "levelname": "DEBUG", "message": "ApplyDataModel :Creating feature class RedlinePointMarker"}
{"asctime": "2020-03-26 17:12:09,371", "levelname": "DEBUG", "message": "ApplyDataModel :RedlinePointMarker created"}
{"asctime": "2020-03-26 17:12:09,372", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtredlinedatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 17:12:09,372", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Label"}
{"asctime": "2020-03-26 17:12:10,939", "levelname": "DEBUG", "message": "ApplyDataModel :Field Label added to C:/Cloud/Dropbox/Work/Axin/rdtredlinedatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 17:12:10,940", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Comments"}
{"asctime": "2020-03-26 17:12:12,613", "levelname": "DEBUG", "message": "ApplyDataModel :Field Comments added to C:/Cloud/Dropbox/Work/Axin/rdtredlinedatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 17:12:12,613", "levelname": "DEBUG", "message": "ApplyDataModel :Applying OBJECTID"}
{"asctime": "2020-03-26 17:12:13,060", "levelname": "DEBUG", "message": "ApplyDataModel :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 17:12:13,061", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 17:12:13,061", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 17:12:13,062", "levelname": "DEBUG", "message": "ApplyDataModel :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 17:12:14,680", "levelname": "DEBUG", "message": "ApplyDataModel :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtredlinedatamodel.gdb/RedlinePointMarker"}
{"asctime": "2020-03-26 17:12:14,681", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'RedlineLineMarker', 'geometry': 'POLYLINE', 'spatialref': 'AlbersEqualAreaConic', 'fields': 'redlinelinemarker.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 17:12:14,904", "levelname": "DEBUG", "message": "ApplyDataModel :Creating feature class RedlineLineMarker"}
{"asctime": "2020-03-26 17:12:16,707", "levelname": "DEBUG", "message": "ApplyDataModel :RedlineLineMarker created"}
{"asctime": "2020-03-26 17:12:16,708", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtredlinedatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 17:12:16,709", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Label"}
{"asctime": "2020-03-26 17:12:18,303", "levelname": "DEBUG", "message": "ApplyDataModel :Field Label added to C:/Cloud/Dropbox/Work/Axin/rdtredlinedatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 17:12:18,304", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Comments"}
{"asctime": "2020-03-26 17:12:19,967", "levelname": "DEBUG", "message": "ApplyDataModel :Field Comments added to C:/Cloud/Dropbox/Work/Axin/rdtredlinedatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 17:12:19,968", "levelname": "DEBUG", "message": "ApplyDataModel :Applying OBJECTID"}
{"asctime": "2020-03-26 17:12:20,355", "levelname": "DEBUG", "message": "ApplyDataModel :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 17:12:20,356", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 17:12:20,356", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 17:12:20,359", "levelname": "DEBUG", "message": "ApplyDataModel :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 17:12:22,180", "levelname": "DEBUG", "message": "ApplyDataModel :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtredlinedatamodel.gdb/RedlineLineMarker"}
{"asctime": "2020-03-26 17:12:22,181", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'RedlineComment', 'geometry': '', 'spatialref': '', 'fields': 'redlinecomment.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 17:12:22,221", "levelname": "DEBUG", "message": "ApplyDataModel :Creating table RedlineComment"}
{"asctime": "2020-03-26 17:12:24,358", "levelname": "DEBUG", "message": "ApplyDataModel :RedlineComment created"}
{"asctime": "2020-03-26 17:12:24,359", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdtredlinedatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 17:12:24,360", "levelname": "DEBUG", "message": "ApplyDataModel :Applying ApprovalStatus"}
{"asctime": "2020-03-26 17:12:25,991", "levelname": "DEBUG", "message": "ApplyDataModel :Field ApprovalStatus added to C:/Cloud/Dropbox/Work/Axin/rdtredlinedatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 17:12:25,992", "levelname": "DEBUG", "message": "ApplyDataModel :Applying Comment"}
{"asctime": "2020-03-26 17:12:27,704", "levelname": "DEBUG", "message": "ApplyDataModel :Field Comment added to C:/Cloud/Dropbox/Work/Axin/rdtredlinedatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 17:12:27,705", "levelname": "DEBUG", "message": "ApplyDataModel :Applying OBJECTID"}
{"asctime": "2020-03-26 17:12:28,129", "levelname": "DEBUG", "message": "ApplyDataModel :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 17:12:28,129", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 17:12:28,130", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 17:12:28,131", "levelname": "DEBUG", "message": "ApplyDataModel :Applying RedlineFeatureId"}
{"asctime": "2020-03-26 17:12:29,777", "levelname": "DEBUG", "message": "ApplyDataModel :Field RedlineFeatureId added to C:/Cloud/Dropbox/Work/Axin/rdtredlinedatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 17:12:29,777", "levelname": "DEBUG", "message": "ApplyDataModel :Applying RedlineCommentId"}
{"asctime": "2020-03-26 17:12:31,500", "levelname": "DEBUG", "message": "ApplyDataModel :Field RedlineCommentId added to C:/Cloud/Dropbox/Work/Axin/rdtredlinedatamodel.gdb/RedlineComment"}
{"asctime": "2020-03-26 17:12:31,501", "levelname": "DEBUG", "message": "ApplyDataModel :Processing feature classes finished."}
{"asctime": "2020-03-26 17:14:44,407", "levelname": "DEBUG", "message": "ApplyDataModel :Class:ApplyDataModel"}
{"asctime": "2020-03-26 17:14:44,409", "levelname": "DEBUG", "message": "ApplyDataModel :loaded config for ApplyDataModel from c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.json"}
{"asctime": "2020-03-26 17:14:44,410", "levelname": "DEBUG", "message": "ApplyDataModel :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas"}
{"asctime": "2020-03-26 17:14:44,410", "levelname": "DEBUG", "message": "ApplyDataModel :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas/prjs/prjs.gdb"}
{"asctime": "2020-03-26 17:17:00,462", "levelname": "DEBUG", "message": "ApplyDataModel :Class:ApplyDataModel"}
{"asctime": "2020-03-26 17:17:00,464", "levelname": "DEBUG", "message": "ApplyDataModel :loaded config for ApplyDataModel from c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.json"}
{"asctime": "2020-03-26 17:17:00,465", "levelname": "DEBUG", "message": "ApplyDataModel :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas"}
{"asctime": "2020-03-26 17:17:00,465", "levelname": "DEBUG", "message": "ApplyDataModel :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas/prjs/prjs.gdb"}
{"asctime": "2020-03-26 17:19:36,146", "levelname": "DEBUG", "message": "ApplyDataModel :Class:ApplyDataModel"}
{"asctime": "2020-03-26 17:19:36,149", "levelname": "DEBUG", "message": "ApplyDataModel :loaded config for ApplyDataModel from c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.json"}
{"asctime": "2020-03-26 17:19:36,150", "levelname": "DEBUG", "message": "ApplyDataModel :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas"}
{"asctime": "2020-03-26 17:19:36,150", "levelname": "DEBUG", "message": "ApplyDataModel :c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass/schemas/prjs/prjs.gdb"}
{"asctime": "2020-03-26 17:19:44,653", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain AssociatedStructType"}
{"asctime": "2020-03-26 17:20:07,305", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:07,306", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:08,860", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain TrueFalse"}
{"asctime": "2020-03-26 17:20:08,861", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:08,861", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:10,264", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain FeederCableSize"}
{"asctime": "2020-03-26 17:20:10,265", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:10,265", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:13,556", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain DistributionCableSize"}
{"asctime": "2020-03-26 17:20:13,556", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:13,557", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:16,606", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain DropCableSize"}
{"asctime": "2020-03-26 17:20:16,607", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:16,607", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:17,295", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain TerminalCableSize"}
{"asctime": "2020-03-26 17:20:17,296", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:17,296", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:19,725", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain TerminalCableType"}
{"asctime": "2020-03-26 17:20:19,725", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:19,726", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:20,426", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain FeederCableType"}
{"asctime": "2020-03-26 17:20:20,427", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:20,427", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:21,141", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain DistributionCableType"}
{"asctime": "2020-03-26 17:20:21,142", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:21,142", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:21,872", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain DropCableType"}
{"asctime": "2020-03-26 17:20:21,873", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:21,873", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:22,581", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain DipType"}
{"asctime": "2020-03-26 17:20:22,582", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:22,582", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:23,278", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain StoredSlackLength"}
{"asctime": "2020-03-26 17:20:23,278", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:23,278", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:26,320", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain SplitterType"}
{"asctime": "2020-03-26 17:20:26,321", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:26,322", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:31,421", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain FiberTerminalType"}
{"asctime": "2020-03-26 17:20:31,422", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:31,423", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:35,410", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain FiberTerminalTail"}
{"asctime": "2020-03-26 17:20:35,410", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:35,410", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:38,870", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain Colour"}
{"asctime": "2020-03-26 17:20:38,870", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:38,871", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:41,256", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain SplitterAreaType"}
{"asctime": "2020-03-26 17:20:41,256", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:41,257", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:42,532", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain TerminalAreaType"}
{"asctime": "2020-03-26 17:20:42,533", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:42,534", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:43,429", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain ConduitInstallationType"}
{"asctime": "2020-03-26 17:20:43,430", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000837: The workspace is not the correct workspace type.\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:43,431", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000837: The workspace is not the correct workspace type.\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:44,038", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value 0 to ConduitInstallationType"}
{"asctime": "2020-03-26 17:20:58,460", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-03-26 17:20:58,461", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 110, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-03-26 17:20:59,881", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain StrandInstallationType"}
{"asctime": "2020-03-26 17:20:59,882", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:20:59,883", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:00,602", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain ConduitSize"}
{"asctime": "2020-03-26 17:21:00,603", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:00,603", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:02,308", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain StrandSize"}
{"asctime": "2020-03-26 17:21:02,308", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:02,308", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:02,976", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain PedestalType"}
{"asctime": "2020-03-26 17:21:02,977", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:02,977", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:04,302", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain HandholeType"}
{"asctime": "2020-03-26 17:21:04,303", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:04,303", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:06,795", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain SpliceEnclosureType"}
{"asctime": "2020-03-26 17:21:06,796", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:06,796", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:08,062", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain CabinetType"}
{"asctime": "2020-03-26 17:21:08,063", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:08,063", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:12,382", "levelname": "DEBUG", "message": "ApplyDataModel :Can't add coded value hh_288F to CabinetType"}
{"asctime": "2020-03-26 17:21:12,383", "levelname": "ERROR", "message": "ApplyDataModel :ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-03-26 17:21:12,383", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 110, in _process_domains\n    arcpy.AddCodedValueToDomain_management(self._connection,k, convert_code, dvalue)\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1696, in AddCodedValueToDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1693, in AddCodedValueToDomain\n    retval = convertArcObjectToPythonObject(gp.AddCodedValueToDomain_management(*gp_fixargs((in_workspace, domain_name, code, code_description), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: ERROR 000535: Workspace does not exist.\nFailed to execute (AddCodedValueToDomain).\n"}
{"asctime": "2020-03-26 17:21:13,819", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain ChamberType"}
{"asctime": "2020-03-26 17:21:13,820", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:13,820", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:14,654", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain PoleType"}
{"asctime": "2020-03-26 17:21:14,655", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:14,655", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:15,469", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain WorkAreaArchitecture"}
{"asctime": "2020-03-26 17:21:15,469", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:15,470", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:16,928", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain WorkAreaCableType"}
{"asctime": "2020-03-26 17:21:16,928", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:16,929", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:18,417", "levelname": "DEBUG", "message": "ApplyDataModel :Can't create domain WorkAreaStatus"}
{"asctime": "2020-03-26 17:21:18,417", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:18,418", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 102, in _process_domains\n    arcpy.CreateDomain_management(self._connection,k,v['description'],v['type'],v['domaintype'],v['split'],v['merge'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1865, in CreateDomain\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 1862, in CreateDomain\n    retval = convertArcObjectToPythonObject(gp.CreateDomain_management(*gp_fixargs((in_workspace, domain_name, domain_description, field_type, domain_type, split_policy, merge_policy), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000192: Invalid value for Domain Name\nFailed to execute (CreateDomain).\n"}
{"asctime": "2020-03-26 17:21:21,630", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'Assembly', 'geometry': '', 'spatialref': '', 'fields': 'assembly.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 17:21:21,670", "levelname": "DEBUG", "message": "ApplyDataModel :Creating table Assembly"}
{"asctime": "2020-03-26 17:21:24,291", "levelname": "DEBUG", "message": "ApplyDataModel :Assembly created"}
{"asctime": "2020-03-26 17:21:24,292", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdt.design.datamodel.gdb/Assembly"}
{"asctime": "2020-03-26 17:21:24,293", "levelname": "DEBUG", "message": "ApplyDataModel :Applying OBJECTID"}
{"asctime": "2020-03-26 17:21:24,872", "levelname": "DEBUG", "message": "ApplyDataModel :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 17:21:24,872", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 17:21:24,873", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 17:21:24,875", "levelname": "DEBUG", "message": "ApplyDataModel :Applying AssemblyId"}
{"asctime": "2020-03-26 17:21:26,499", "levelname": "DEBUG", "message": "ApplyDataModel :Field AssemblyId added to C:/Cloud/Dropbox/Work/Axin/rdt.design.datamodel.gdb/Assembly"}
{"asctime": "2020-03-26 17:21:26,500", "levelname": "DEBUG", "message": "ApplyDataModel :Applying StructureId"}
{"asctime": "2020-03-26 17:21:27,945", "levelname": "DEBUG", "message": "ApplyDataModel :Field StructureId added to C:/Cloud/Dropbox/Work/Axin/rdt.design.datamodel.gdb/Assembly"}
{"asctime": "2020-03-26 17:21:27,945", "levelname": "DEBUG", "message": "ApplyDataModel :Applying RUSCode"}
{"asctime": "2020-03-26 17:21:29,417", "levelname": "DEBUG", "message": "ApplyDataModel :Field RUSCode added to C:/Cloud/Dropbox/Work/Axin/rdt.design.datamodel.gdb/Assembly"}
{"asctime": "2020-03-26 17:21:29,418", "levelname": "DEBUG", "message": "ApplyDataModel :{'name': 'AssociatedStructure', 'geometry': '', 'spatialref': '', 'fields': 'associatedstructure.json', 'globalids': True, 'editortracking': True, 'archiving': True, 'attachments': False}"}
{"asctime": "2020-03-26 17:21:29,458", "levelname": "DEBUG", "message": "ApplyDataModel :Creating table AssociatedStructure"}
{"asctime": "2020-03-26 17:21:31,707", "levelname": "DEBUG", "message": "ApplyDataModel :AssociatedStructure created"}
{"asctime": "2020-03-26 17:21:31,708", "levelname": "DEBUG", "message": "ApplyDataModel :Applying fields for C:/Cloud/Dropbox/Work/Axin/rdt.design.datamodel.gdb/AssociatedStructure"}
{"asctime": "2020-03-26 17:21:31,709", "levelname": "DEBUG", "message": "ApplyDataModel :Applying OBJECTID"}
{"asctime": "2020-03-26 17:21:32,148", "levelname": "DEBUG", "message": "ApplyDataModel :Adding field OBJECTID failed"}
{"asctime": "2020-03-26 17:21:32,149", "levelname": "ERROR", "message": "ApplyDataModel :Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 17:21:32,150", "levelname": "ERROR", "message": "Traceback as follows:", "exc_info": "Traceback (most recent call last):\n  File \"c:\\Cloud\\Dropbox\\Work\\Axin\\Python\\CreateFeatureClass\\ApplyDataModel.py\", line 160, in _process_fields\n    arcpy.AddField_management(fc,fd['name'],fd['type'],fd['precision'],fd['scale'],fd['length'],fd['alias'],fd['nullable'],fd['required'],fd['domain'])\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4170, in AddField\n    raise e\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 4167, in AddField\n    retval = convertArcObjectToPythonObject(gp.AddField_management(*gp_fixargs((in_table, field_name, field_type, field_precision, field_scale, field_length, field_alias, field_is_nullable, field_is_required, field_domain), True)))\n  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 511, in <lambda>\n    return lambda *args: val(*gp_fixargs(args, True))\narcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.\nWARNING 000012: OBJECTID already exists\nERROR 000800: The value is not a member of Text | Float (single precision) | Double (double precision) | Short (small integer) | Long (large integer) | Date | Blob (binary data) | Raster imagery | GUID (globally unique identifier).\nFailed to execute (AddField).\n"}
{"asctime": "2020-03-26 17:21:32,152", "levelname": "DEBUG", "message": "ApplyDataModel :Applying StructureId"}
{"asctime": "2020-03-26 17:21:33,627", "levelname": "DEBUG", "message": "ApplyDataModel :Field StructureId added to C:/Cloud/Dropbox/Work/Axin/rdt.design.datamodel.gdb/AssociatedStructure"}
{"asctime": "2020-03-26 17:21:33,628", "levelname": "DEBUG", "message": "ApplyDataModel :Applying CableId"}
{"asctime": "2020-03-26 17:21:34,882", "levelname": "DEBUG", "message": "ApplyDataModel :Field CableId added to C:/Cloud/Dropbox/Work/Axin/rdt.design.datamodel.gdb/AssociatedStructure"}
{"asctime": "2020-03-26 17:21:34,883", "levelname": "DEBUG", "message": "ApplyDataModel :Applying StructureType"}
